### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Shadowkain85** [FTBTeam/FTB-Quests#102]
Would it be possible to create skin packs, in a similar manner to better questing mod, that allows for the user/developer to define how FTBQuests looks, not just the icons but the BG's, Tabs etc. I feel this may help some mod packs to be fairly immersive in how they are presented, like a fallout theme for a fallout themed mod pack, as an example?

**Comment by LatvianModder** [comment]
This is the background image:

[![](https://github.com/LatvianModder/FTBLib/blob/master/src/main/resources/assets/ftblib/textures/gui/background_squares.png)](https://github.com/LatvianModder/FTBLib/blob/master/src/main/resources/assets/ftblib/textures/gui/background_squares.png)

**Comment by Shadowkain85** [comment]
It was mainly for the background picture, quest icons, and possibly the colours of the flowing arrows and tabs borders that I had in mind. So if its as easy as just changing the background image as it stands could this in theory be currently done by use of a resource pack for FTBQuests?

**Comment by LatvianModder** [comment]
Yeah, ftblib/ftbquests. Changing colors can be added too easily, via quest file itself, but changing tabs might be difficult. Still, it uses the same background image, so it should mostly look fine

**Comment by Shadowkain85** [comment]
Cheers thank you

**Comment by RossAndrewMatthews** [comment]
So, how does one go about changing the background image. I have some visually impaired players on the server.

**Comment by ftrocchi** [comment]
The other tickets I put in were closed and referenced to this one.  I want to chime in that this isn't necessary for athletics... but it is for the visually impaired.  We need the ability to change the looks so things can stand out and be visible.  Otherwise it becomes unplayable.

**Comment by LatvianModder** [comment]
I updated my response in this issue

**Comment by ftrocchi** [comment]
oh thanks :)  Uhm.. I didn't see that :)  visually impared is awful

**Comment by CursedWarrior10HD** [comment]
It would be really cool

If you think it will take some time then you can make the background the color you want by HTML like the Crates
