### ISSUE TITLE
IC2 Energy detection seems to be not working

### ISSUE THREAD

**Issue by davqvist** [FTBTeam/FTB-Quests#111]
FTB Quests 1.3.4.95
I did setup the screen just like the one for Forge Energy which works out just fine, but I have a Full MFSU connected with a cable to the screen and the quest doesn't update/increase. I tried with or without cable, a Coal Generator attached to it and much more without luck. Here is a screenshot of my setup: https://i.imgur.com/1V2Gdo5.png

**Comment by LatvianModder** [comment]
Hm. Try placing generator or solar panel next to it. There was something weird about EU and high voltage

**Comment by davqvist** [comment]
Like I said I tried. I used a normal Coal Generator and placed it next to it. Didn't work either.

**Comment by LatvianModder** [comment]
Seems to be working now

**Comment by LatvianModder** [comment]
![image](https://user-images.githubusercontent.com/3844385/58954948-41827b00-87a3-11e9-9074-99bef5a1bcbe.png)
Even tried with 3 different methods - solar panel, coal generator and MSFU directly plugged in screen
