### ISSUE TITLE
NBT Items not showing

### ISSUE THREAD

**Issue by MeinKraft** [FTBTeam/FTB-Quests#123]
MC 1.12.2
FTB Quests 1.4.0.109
FTBLib 5.4.0.73

Ive noticed some items from Mob Grinding Utils (version 0.3.12) dont show up in the item list when making a quest
In my modpack the Mob Masher Fan items have ID 5396:0 to 5396:2 and Mob Masher Upgrades 5398:0 to 5398:5  None of which show in the items list when creating a quest

Also I removed Ex Nihilo Creatio Crucible recipe (ID 4988:0) and changed the recipe for the Fired Crucible (ID 4988:1)  and the Fired Crucible also does not appear in the items list

some pictures  https://imgur.com/gallery/5IEMrcA

**Comment by LatvianModder** [comment]
I read the list directly from vanilla search tab, so if some items don't show up there, it's probably mod's fault and nothing much I can do. You can add items from your inventory by clicking on compass though
