### ISSUE TITLE
Theme is difficult for visually impaired

### ISSUE THREAD

**Issue by grannymc** [FTBTeam/FTB-Quests#130]
I see others have commented on the colors. I just want to add that I am visually impaired. While the colors look nice, they are unfortunately very hard for me to read. More contrast and use of brighter colors would help a lot. Otherwise, a very nice mod.

**Comment by ircmaan** [comment]
It is very important: I need switch background to light and WITHOUT transparency.
It is questsBOOK. 
Thanx.

**Comment by LatvianModder** [comment]
Will be part of https://github.com/FTBTeam/FTB-Quests/issues/102

**Comment by ftrocchi** [comment]
This shouldn't be closed until addressed, because it is addressing a different issue than #102.
