### ISSUE TITLE
Team reward configuration is unclear/broken

### ISSUE THREAD

**Issue by MrNinja93** [FTBTeam/FTB-Quests#132]
Your wiki page on curseforge states the following 

``Click on reward button to claim a reward. If the reward name is blue, then it means only one person can claim the reward, otherwise, everyone on team will get a copy.``

In game however any reward with a blue name has the [Team Reward] tag... 

In-case it's needed
Forge 2796
FTB quests 1.4.0.109
FTB Utilities 5.3.0.68
FTB Lib 5.4.0.73

**Comment by Johnyxiade** [comment]
Curious on this myself. Is there any way to config this to where everyone on the team does get a random reward when a quest is claimed?

**Comment by LatvianModder** [comment]
I agree that it's unclear. Its called Team Reward, because in my head it stands for "A reward for team not for player, thus Team Reward". I'll figure out how to rename it.

**Comment by LatvianModder** [comment]
Updated docs
