### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by Slowwloriss** [FTBTeam/FTB-Quests#137]
Hi! maybe other people had suggested that but idk.

Possibility for hide quests and chapters, hide lines (this maybe with variables should work).
If the quest is "unavailable" because have dependency, when you hover with the mouse or click it say something like ( you dont have discover this quest) or something like that instead of show you the whole quest. I think that will do Quests more interesting and people can be more creative. 
Compatibility with lang files for localize Quests.
Great mod!

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/14
