### ISSUE TITLE
Need ability to change color/contrast to see the quests

### ISSUE THREAD

**Issue by ftrocchi** [FTBTeam/FTB-Quests#138]
The quest features are not ADA (Americans with Disabilities Act) compliant, and this needs to be fixed to be usable by those that are legally blind.  Though they can see, they have trouble seeing darkened quests (unavailable ones as an example) on a dark background.  

Provide a means for the user to change how the quest feature looks, such as implementing themes, or changing colors / brightness.

As it stands, many users are being left out because they simply cannot see to play.

**Comment by LatvianModder** [comment]
This will be part of https://github.com/FTBTeam/FTB-Quests/issues/102
