### ISSUE TITLE
Resetting Quests Doesnt Reset Rewards

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-Quests#139]
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/53
When you enable FTB-QUEST Editing mode and reset all quests you cant collect rewards from the quests if re-completing them

**Comment by SansDerp** [comment]
Can confirm, I reset the quests through trying to join another team and going to another island but the rewards are still "redeemed."

**Comment by marx1** [comment]
Deleting and re-creating your team resets quests, but doesn't reset rewards as well.
