### ISSUE TITLE
Implement quest Visibility

### ISSUE THREAD

**Issue by CindyLouWho03** [FTBTeam/FTB-Quests#14]
Make it so that when quests arent duable they are hidden from the grid and will reappear once the dependency quest is done

**Comment by LatvianModder** [comment]
It's supposed to be like that already, but I think I havent implemented/fixed that

**Comment by ilvrak** [comment]
not understand how the new visibility modes work. 'secret', 'invisible' - does nothing on non dependent quest.
can we make the quest invisible until it task is completed? then he appears so that we take the rewards

**Comment by LatvianModder** [comment]
I could add that mode. It currently only hides/disables quest if dependencies arent met. There will be explanation on the modes later in wiki

**Comment by silvenlily** [comment]
I think this needs to be re-opened for 1.16.4?
Either that or I'm dumb 50/50 odds.
