### ISSUE TITLE
Quests leaderboard

### ISSUE THREAD

**Issue by AK9Official** [FTBTeam/FTB-Quests#143]
So I'm curious... Would it be hard to integrate Quests into the FTB Utilities leaderboards? I was thinking having a leaderboard that displays which that has completed the most quests... (Mainly a feature for multiplayer). It would create some kind of "competition" to complete all quests within a pack, you would have more to do as people don't tend to complete all quests before they call the pack "finished".

**Comment by LatvianModder** [comment]
I could do that, but leaderboards are player based but quests are team based..
