### ISSUE TITLE
Completely Broken Quest GUI other than one corner

### ISSUE THREAD

**Issue by voidegg** [FTBTeam/FTB-Quests#145]
ftb lib ver:5.4.1.77

ftb quest ver:1.4.1.115

screen shots

![](https://user-images.githubusercontent.com/42865598/47655575-ef86d080-db95-11e8-8375-b71358c804f3.png)
:

**Comment by LatvianModder** [comment]
Hmm seems to be the same as https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/50

**Comment by LatvianModder** [comment]
Does it happen every time?
Do you have any extra mods from modpack installed?
Can you close the gui and continue playing?

**Comment by LatvianModder** [comment]
Images of other similar issues:
![](https://user-images.githubusercontent.com/42865598/47655575-ef86d080-db95-11e8-8375-b71358c804f3.png)
![](https://user-images.githubusercontent.com/49423260/55844546-64761300-5b03-11e9-9a0c-bb26bf9acc33.jpg)

**Comment by LatvianModder** [comment]
@voidegg @ShadowsPlayer @eldrazijon
It's most likely a hardware issue.
What are your graphic card models?
And does this happen every time you open the book?
Does it make the interface unusable?

**Comment by Slowwloriss** [comment]
I saw that Blue screen once, when i opened the book, but pressed ESC and reopened the book and worked well. MSI X GTX1080

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in 1.16+ versions of Quests anymore, hopefully
