### ISSUE TITLE
Quest choices

### ISSUE THREAD

**Issue by mr-poyo** [FTBTeam/FTB-Quests#146]
Is it possible to add quest choices with respective rewards? 

For example, Quest called 'Make your Choice:' 
You are forced to choose between killing a zombie or killing a pig. Killing the zombie would provide its own unique reward and set the quest as complete.

Or, killing the pig would have resulted in a different reward and set quest as complete. If it's possible, thank you!!

**Comment by LatvianModder** [comment]
I will be adding "Undependencies" soon (I need a better name for that) which will basically allow you to lock one quest tree after you complete another one. Basically what your request is

**Comment by sadface-0** [comment]
Maybe 'conditional'
If this then that 👍

Thanks for your hard work
