### ISSUE TITLE
Unable to open FTB Loot Crate

### ISSUE THREAD

**Issue by remclave** [FTBTeam/FTB-Quests#149]
I am unable to open the loot crate.

I just loaded a new instance of Sky Adventures (**version 1.4.0**) and have just started the first quests. Received a "Old Loot Crate" that I converted per the written instructions but cannot figure out how to interact with it to "open" the crate. Don't know if this is a bug or if I just missed some instructions on how to open it. I cannot find any information because Google Fu brings up the Loot Crate website that sells swag.

eta: This is an instance on a server running the latest release as shown above. No additional modifications have been made to this server except to add Lagbgone and AFK kick timer.

**Comment by LatvianModder** [comment]
That seems like a modpack bug. You should be able to just right-click with it in hand to open it

**Comment by remclave** [comment]
I tested in a single-player world and the crate works by right-clicking. I will report it to the Sky Adventures github.
