### ISSUE TITLE
[Suggestion] Locked Chapters

### ISSUE THREAD

**Issue by CritFlaw** [FTBTeam/FTB-Quests#151]
It would be nice of chapters could be unlocked via game-stages, a command, whatever. Similar to Triumph or Better Questing. There are many applications for this but one example that's a little different is a pack I'm developing where there is a skyblock and an overworld, and the quests are different depending on which you choose to start with.

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/14
https://github.com/FTBTeam/FTB-Quests/issues/33
