### ISSUE TITLE
[request] hide locked quest

### ISSUE THREAD

**Issue by RealLith** [FTBTeam/FTB-Quests#153]
an option to make quest hidden if they are locked.
For example:
You have quests: A B C

A quest is unlocked and therefor you may complete it.
Quest B and C are locked.
quests B and C wont be showed unless A is completed.

Additional. lets say you have quests A B C D
in order to unlock quest D u need to do quest C and B. A quests unlocks B and C. B and C wont be unlocked (showed in the quest book) unless A is completed. Quest D, on the other hand, will be showed in the quest book if quest B or C is finished but wont be unlocked to be completed (basically u need at-least 1 dependency to be finished to show the next quest even tho, if has more then 1 dependencies, other dependencies are not done..

In addition to this it would be awesome if we could make chapters that have 100% locked quest not display. only if at-least 1 quest is unlocked then load in the chapter OR at-least load a chapter after finishing a quest (include dependency).

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/14
