### ISSUE TITLE
[Request] Command and permissions list

### ISSUE THREAD

**Issue by Column01** [FTBTeam/FTB-Quests#154]
Just wondering if we could get a command list, and the permissions for them? I was looking at the actually commands in the mod and was pulling out commands but I have no idea how the permissions are handled and such, and was wondering if there was some list somewhere that I could have.
I know OP gives the perms needed, but we do not like giving out OP unless we absolutely have too.

**Comment by Column01** [comment]
I found [this list](https://gist.github.com/78f4bb2019f4469cafcbaeec9a6280b7) in the server files, but none of the permissions for FTB quests are allowing me to use the commands.

**Comment by LatvianModder** [comment]
I don't know anything about luck perms, all commands for FTB Quests are under /ftbquests. You must enable editing mode for player to use them though, with /ftbquests editing_mode
