### ISSUE TITLE
Extra Quest (Repeatables) not working

### ISSUE THREAD

**Issue by Daedelon** [FTBTeam/FTB-Quests#156]
I'm on Version 1.4.0.109 for FTB Quests and I have complete various quests in all the chapters and it seems to be working fine except when I wanted to turn in a repeatable quest in the Extra Quests tab.  I had created an Iron Drum filled with Creosote Oil and clicking the Submit button does nothing.  And I had created a Quest Chest and it won't allow me to put it in the Input Slot.

**Comment by LatvianModder** [comment]
That's quite an outdated mod version, reopen if you can do the same with latest
