### ISSUE TITLE
FTB Quests Permissions

### ISSUE THREAD

**Issue by Column01** [FTBTeam/FTB-Quests#162]
Setting the permissions nodes using the nodes listed in your command classes does not work. Any server administrator who serves more than just themselves cannot just use your proprietary permission system to allow commands, and the permission nodes should be made to work with SpongeForge and permission management systems such as LuckPerms. 

By default, `/ftbquests editing_mode` is linked to OP, which most networks with staff do not give out and just give permission nodes via a permissions system such as LuckPerms. You can specify permission groups using FTBLibs as listed on my other issue, but it is NOT a perfect solution by far as it is not integrated into existing permissions systems, and it is server specific.

Right now, your permission nodes follow an improper format. It should be like `ftbquests.command` and not `commands.ftbquest` like it is at the moment to follow the standard for other mods/plugins. You closed my issue earlier without even letting myself explain so I made another one to discuss this. Please don't just close an active issue without waiting for a response.

What I want to know is there a way around having to use the FTB proprietary permissions system or are we forced to use it if we do not want to give out OP to our staff?

#154

**Comment by Column01** [comment]
I just used a feature of Luck Perms to check for permission nodes checked against my player, and it came back with nothing. Does the `/ftbquests editing_mode` command set it for the entire server or for just that player? The source code points to it checking a user permission and then setting it for that user but this permission sniffer is showing that this is not the case.

**Comment by TheVeyra** [comment]
Using Luck Perms, I had to give the permission node "editing_mode" in order to use /ftbquests editing_mode. As you said, it's the improper perm node format but it works. Using the command sets it for just the player.

**Comment by Column01** [comment]
> Using Luck Perms, I had to give the permission node "editing_mode" in order to use /ftbquests editing_mode. As you said, it's the improper perm node format but it works. Using the command sets it for just the player.

So you set the permission node `editing_mode` for a group or user in luck perms and it allowed you to use it?

**Comment by TheVeyra** [comment]
Yes, I set `editing_mode` as the permission node and I was able to use the command.

**Comment by Column01** [comment]
So that works for editing mode, but other ones such as `reset_progress`. I'm a little sick and tired of this to be honest. Every other mod written by any competent developer has permission nodes that work regardless of the system you use, but apparently FTB quests is the outlier.

**Comment by TheVeyra** [comment]
Once you run `/ftbquests editing_mode` and you are in editing mode, you can use the other commands. As far as I can tell, you can't set a permission node for them, you just have to be in editing mode.

**Comment by Column01** [comment]
Guess I'll close this... Still needs to get their stuff together.

**Comment by LatvianModder** [comment]
Blame LuckPerms, they should handle CommandTreeBase properly, which is part of Forge, and not something custom only in my mod.

**Comment by Column01** [comment]
It's not LP. It's the way you've coded it. It would happen with zPerms or even setting it using the permissions.yml file. Your permission nodes don't follow proper format, LP doesn't do anything but deny or allow them. Every other mod that has commands uses proper syntax and has no issues.
You need better documentation also.

**Comment by LatvianModder** [comment]
What permission nodes? My commands don't have any permission nodes. Does it work properly with /forge tps and /forge generate commands?

**Comment by Column01** [comment]
Yes. It works for all mods/plugins or datapacks. As long as the permissions are setup with this in mind. If its built to rely on a proprietary permission system or its linked to OP in a way that doesn't use permission nodes, it doesn't work.

Like I've been trying to say, it is the way the mod is coded causing these issues

**Comment by pyscho974** [comment]
minecolonies also uses OP level settings to allow its use of commands. rather annoying really
