### ISSUE TITLE
Quests on server

### ISSUE THREAD

**Issue by Lolisemo** [FTBTeam/FTB-Quests#166]
I have a client with a LARGE line of quests, and I need to transfer these quests to the server. How to do it? If I just add the questpacks folder to the folder of the server, the server will not start.Please help me!!!! 
Quests really large number and redo them all would take a long time

**Comment by LatvianModder** [comment]
If it doesn't start, is there a crash report?

**Comment by Lolisemo** [comment]
The server began to start without any problems. Sorry to bother you.(I don't know why it crash before)
