### ISSUE TITLE
Dependencie crash

### ISSUE THREAD

**Issue by brachy84** [FTBTeam/FTB-Quests#169]
When i set the the dependencies of two quests to each other the game crashes and i can't go into a world to fix it because it crashes when i join a world
https://pastebin.com/xxKXdsFP

**Comment by brachy84** [comment]
And now all 752 quests are gone FUCK

**Comment by brachy84** [comment]
But thankfully I'm a smart person and made backup so only a few quests are lost

**Comment by CursedWarrior10HD** [comment]
****thanks for the Idea for the backup of the quests__**
