### ISSUE TITLE
Better highlighting of currently selected quest

### ISSUE THREAD

**Issue by GrumpyChunks** [FTBTeam/FTB-Quests#170]
Would it be possible to better highlight the currently selected quest? It might just be me, but whenever I open the quest interface with a quest selected, it's difficult to tell which one is actually selected. I believe it would be better if the selected quest had a much stronger highlight e.g. a bright yellow glow around the icon maybe?

I often find myself clicking on the quest I'm interested in, only to find I've deselected it, because it was already the selected one.

I hope I've explained this clearly, if not please advise and I'll create a mock up of what I mean.

**Comment by CursedWarrior10HD** [comment]
Just adding to your request, there a should be an HTML color chooser in the settings to make the highlight the color you want like in the crates.
![capture](https://user-images.githubusercontent.com/42890303/53176196-7c421800-35e5-11e9-9703-3ea695451be4.PNG)

**Comment by MaxNeedsSnacks** [comment]
This *should* no longer be relevant since Quests now auto-open when you click them ^^
