### ISSUE TITLE
[Feature Request] to be able to select multiple quests 

### ISSUE THREAD

**Issue by CursedWarrior10HD** [FTBTeam/FTB-Quests#171]
I'm making a modpack with over 500 quests and it takes me a very long time set the item "a single "on the rewards and I would like to be able to hold SHIFT and select multiple quests and do set reward "Item" and it would set the selected item a reward on all of the quests I've selected . please add this feature because I want to make a modpack using this mod with over 500+quests.

**Comment by LatvianModder** [comment]
You can, ctrl+click on quests
