### ISSUE TITLE
[request] true filenames or a hybrid

### ISSUE THREAD

**Issue by kreezxil** [FTBTeam/FTB-Quests#174]
When viewing the chapters, quests, etc in the new location in the ftbquests folder all the names there are according to the ids. Would like the option to name a chapter and quest and that appear as the alternative to the id based filename.

A good middle ground would be a deliminated filename such that it might be id-readable for example `8d8g38d-kill_the_monkey.nbt`, in this way we can easily identify them in the file system.

**Comment by LatvianModder** [comment]
I wanted to do that, but it would make changing titles and merging chapters a nightmare, so, no.
