### ISSUE TITLE
Dependency loop crash still possible

### ISSUE THREAD

**Issue by Funwayguy** [FTBTeam/FTB-Quests#178]
If an editor is not using `Set Selected as Dependency` in the context menu but instead uses the edit screen, it is still possible to create a quest dependency loop (either accidentally or intentionally) and crash the game.

Example:
![image](https://user-images.githubusercontent.com/6048596/53380987-fe9e5380-39ba-11e9-9bd8-cb9289569a18.png)

Crash attempting to use context menu to set the potion quest as a dependency to the stone block:
[crash-2019-02-26_11.38.43-client.txt](https://github.com/FTBTeam/FTB-Quests/files/2903371/crash-2019-02-26_11.38.43-client.txt)

**Comment by LatvianModder** [comment]
Well, that's on you if you do it purposely, but I will fix this ofc :P
