### ISSUE TITLE
Dependencies ore gone

### ISSUE THREAD

**Issue by brachy84** [FTBTeam/FTB-Quests#180]
![2019-03-01_19 37 02](https://user-images.githubusercontent.com/45517902/53658662-ac2e9280-3c59-11e9-8017-bcfc07ac6ec8.png)
I saw in changelog that you did something with dependencies, but i don't know if this is a bug or not:
I can't set dependencies over quest pages via the Dependencies button because it's gone

**Comment by MaxNeedsSnacks** [comment]
+1 on this, as it stands right now, I think it's actually impossible to add cross-chapter dependencies without NBT editing the file manually.

**Comment by LatvianModder** [comment]
I removed the feature internally, but forgot to re-add properly, because I started working on the editor GUI. It will be re-added next-ish update

**Comment by aaronhowser1** [comment]
*poke*

**Comment by brachy84** [comment]
I neeeed it
