### ISSUE TITLE
Expensive items are consumed and food items are not

### ISSUE THREAD

**Issue by James1524** [FTBTeam/FTB-Quests#182]
I think this is a bug, but all the expensive items are consumed. For instance, for the diamond hammer in order to complete the quest you need to have one made and than click complete quest and it consumes the hammer. This leaves the user having to get the materials again to make the hammer again. This is the same for every expensive item in the game.
![bugged](https://user-images.githubusercontent.com/48171302/53691638-1832f880-3d37-11e9-80f5-7134c419b2b5.png)

**Comment by thetakodev** [comment]
I don't think that's a bug. Are you making a modpack, or playing one?

**Comment by LatvianModder** [comment]
Not a bug in mod, report to modpack
