### ISSUE TITLE
Complete command and Generic Quest

### ISSUE THREAD

**Issue by MeinKraft** [FTBTeam/FTB-Quests#190]
Here is what I hope to achieve:  I have a custom structure that randomly generates in my world at multiple locations.  When the player finds the structure, they press a button and a quest completes.

I cant use the 'Location Task' because the structures spawn in random locations

here are the 2 main problems:

1) I would like a generic quest Task that maybe can only be completed by command, instead of the regular tasks like get a specific item or an amount of fluid

2) If I use the command '/ftbquests change_progress complete 8F25 39c42b7d' then I MUST specify a team.  If I have a Button on top of a Command Block, how do I pass the Team Number to the command?

Maybe add a custom block that when interacted with, it will complete a quest?

Thank you for your time

**Comment by BasieBrinkie** [comment]
I'm currently developing a pack based on gamestages. That does also require me to complete a quest using a command. If you were to integrate team completion in the command itself like splitting it in `/ftbquests change_progress complete --TeamID --QuestID` as it is now and a subcommand `/ftbquests change_progress complete_team --personID --QuestID`. This way I could use @p in the command and complete a quest with the mod researchtables

**Comment by LatvianModder** [comment]
You can use gamestages
