### ISSUE TITLE
Add an option to disable durability bars

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#191]
![image](https://user-images.githubusercontent.com/15698722/54789695-510d1180-4c01-11e9-96c2-e38e4c689628.png)

It'd be better to just be the item texture without the durability bar

**Comment by LatvianModder** [comment]
Durability bar and enchantment effects are rendered in the same function, so for glowing items, you'd be sacrificing that too, but I guess its not such an important loss

**Comment by MaxNeedsSnacks** [comment]
Just use custom images
