### ISSUE TITLE
Non-Team Tasks

### ISSUE THREAD

**Issue by SteveKnowless** [FTBTeam/FTB-Quests#193]
I am looking for an option to allow team members to complete their own individual tasks. For example each member needs to create their own bed. As The system currently is, if someone creates a bed then everyone on the team get credit.

Thanks

**Comment by LatvianModder** [comment]
Sorry, I dont think this will be possible with my mod, because of how teams work, the quests would "uncomplete" when a new member joins team, that would break a lot of things
