### ISSUE TITLE
Progress Screen - Skin setting doesn't work properly

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#196]
I changed it to minecraft:log on the middle right screen block, and a second or two after leaving the menu that column changed texture but the rest didn't.

![image](https://user-images.githubusercontent.com/15698722/54876282-22e32980-4ddb-11e9-8d12-5e0dcd7afd89.png)

**Comment by LatvianModder** [comment]
Can't replicate, probably just needed a block update
