### ISSUE TITLE
When you cancel out of deleting a quest, you can't click on anything until closing and reopening the menu

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#202]
Repeatable, FTBQuests-1.5.1.136

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/54998483-3db0cc00-4f9c-11e9-9b7a-28f53197b276.png)
I think what's happening is that it's stuck on the context menu, but it isn't rendering and doesn't go away when you click off it. Clicking on it doesn't do anything either.

**Comment by freopt** [comment]
I have also had this issue
