### ISSUE TITLE
Hitting E to close the text menu doesn't save the text

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#205]
It saves on every other page, but hitting E to confirm on this screen doesn't save the text.
![image](https://user-images.githubusercontent.com/15698722/55001622-02fe6200-4fa3-11e9-9129-77fc492df767.png)

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue
