### ISSUE TITLE
Clicking for the first time on a text box with text in it doesn't put the cursor where you clicked

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#206]
I wrote this and closed the menu then came back to it to edit it. If I click here:
![image](https://user-images.githubusercontent.com/15698722/55001928-a8b1d100-4fa3-11e9-8cdd-af3edc708bb5.png)
it places the cursor here:
![image](https://user-images.githubusercontent.com/15698722/55001978-bd8e6480-4fa3-11e9-9710-f88cfd1e40a6.png)

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue
