### ISSUE TITLE
Jungle island by KoOo - cant obtain oak wood/finish the 1st mission

### ISSUE THREAD

**Issue by Croompy** [FTBTeam/FTB-Quests#208]
I started a world with the jungle layout, and it is easy to obtain the oak sapling cuz of all the leaves, yes the 1st mission states that i am supposed to get 'oak wood', and does not register with the jungle wood i obtained.
also since there is no dirt on the island im basically stuck.
should probably make the 1st quest work with all tree types (?), unless i was missing something

**Comment by manmaed** [comment]
the storage draw quest will help you get the money to get a normal spaling
