### ISSUE TITLE
Quest Chest  not recognizing partially complete quests

### ISSUE THREAD

**Issue by jelaw21** [FTBTeam/FTB-Quests#219]
I made a quest requesting 512 oak planks. When I open the quest chest, the requirements show up. However, if I only submit 1 stack, close and re-open, it no longer shows the requirement.

**Comment by LatvianModder** [comment]
Quest Chest never should have been added to the mod tbh. It was only designed for FTB Pyramid map

**Comment by jelaw21** [comment]
It's a fabulous tool. Does that philosophy apply to screens as well?

**Comment by LatvianModder** [comment]
No, screens are there to stay, they are the main automation method. Chest was always secondary
