### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by TheSnowyChickens** [FTBTeam/FTB-Quests#220]
Hello,
with v1.5.1.143 I can't start the game.

crash log -> https://paste.dimdev.org/axacexoqiw.mccrash

MC: 1.12.2
Forge: 2825
FTB Lib: 5.4.1.94
FTB Utils: 5.4.0.92
JEI: 4.15.0.275

![grafik](https://user-images.githubusercontent.com/29357962/55819231-99c93380-5af8-11e9-83ff-76510ede39a2.png)

**Comment by LatvianModder** [comment]
Looks like you need to update Item Filters mod

**Comment by TheSnowyChickens** [comment]
I try it.
