### ISSUE TITLE
Crash during startup, mark II

### ISSUE THREAD

**Issue by pyure** [FTBTeam/FTB-Quests#221]
Possibly related to #220, different classes however.

**FTBQuests-1.5.1.143.jar** fails with following error:
https://pastebin.com/yfPXuGiD

forge-14.23.5.2835
FTBLib-5.4.1.94.jar

FTBQuests-1.5.1.141.jar works fine.  Didn't try .142 since it looks like you hot-patched something.

**Comment by TheSnowyChickens** [comment]
:D

I tried it with v142 and v141, but I also get a crash. :(

**Comment by TheSnowyChickens** [comment]
@pyure Update the Item Filters mod, that was my problem.

**Comment by LatvianModder** [comment]
Update Item Filters like snowy said

**Comment by pyure** [comment]
Thanks kindly gentlemen.
