### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-Quests#222]
Issue: After upgrading the best satchel, not creative, with Holding IV it's making my game crash and tell me Cofh core and ftb quests is at fault.

Link to Log or Crash File Paste: https://paste.dimdev.org/umesohegev.mccrash

Is it Repeatable?: Yes, everytime i login to my world it crashes, between 3 and 10 seconds each time

FTBQuests-1.5.1.140.jar

**Comment by Fiskpung** [comment]
I believe i've found the problem, when you have auto loot into satchel it crashes. i deleted it and mined some and i didnt crash.
