### ISSUE TITLE
Crashing when opening quest book

### ISSUE THREAD

**Issue by KittyKitCatCat** [FTBTeam/FTB-Quests#224]
When i open the quests using the UI piece in my inventory, my game crashes. It's a pretty large modpack but it started happening after i addded FTB utilities version 5.4.093. Im using FTBQuests version 1.5.1.143. Has this been fixed in the newer versions, couldn't find anything about it

**Comment by LatvianModder** [comment]
I'm gonna need a crash report, can't tell anything without it
