### ISSUE TITLE
Hitting E to confirm the item menu doesn't save it

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#233]
This is the menu I mean:
![image](https://user-images.githubusercontent.com/15698722/56815775-bc9d5c80-6807-11e9-9a15-28771e98c1b1.png)

It closes the menu but it acts like a cancel button instead of an accept button

**Comment by LatvianModder** [comment]
Tbh, I don't see how this is a bug, Esc and E are both cancel by default, not save

**Comment by aaronhowser1** [comment]
Esc acts as a cancel and E as accept in most other menus (except text *cough cough*).
