### ISSUE TITLE
Language keys for descriptions don't work when hovering over a quest

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#239]
![image](https://user-images.githubusercontent.com/15698722/56913722-07251000-6a78-11e9-9c09-39fad9b833ba.png)

It works on the right, but not in the tooltip thing

**Comment by xinyuan-liu** [comment]
I have the same issue. I've updated FTB-Quests to 1.5.2.150. I18n now works well in the description of a quest when hovering but still doesn't work for description of a Chapter.

**Comment by xinyuan-liu** [comment]
@LatvianModder I think ```com.feed_the_beast.ftbquests.gui.tree.ButtonChapter``` also needs updating for I18n support.
