### ISSUE TITLE
Location Based Task

### ISSUE THREAD

**Issue by CindyLouWho03** [FTBTeam/FTB-Quests#24]
Another useful features i could see added is a way to set a location for you to travel to. This could be particurally useful in a story driven pack, but not for my skyblock, Doesnt need to be done now but still thought it would be useful

**Comment by generrosity** [comment]
@CindyLouWho03  check this out - https://www.youtube.com/watch?v=qe1jzH5ZVaw

A quest for a xyzd location, and able to use a support block to generate the quest faster. Might see a build including it quite soon :D

**Comment by generrosity** [comment]
potentially this one - https://minecraft.curseforge.com/projects/ftb-quests/files/2663351
