### ISSUE TITLE
Problema de tela

### ISSUE THREAD

**Issue by ShadowsPlayer** [FTBTeam/FTB-Quests#242]
Tanho este problema algem me pode ajudar a resolver ?
Eu não tanho o Optifine !
![probleme 1](https://user-images.githubusercontent.com/50246440/57156895-1a691000-6dd7-11e9-902d-d9837a1dc44d.PNG)

**Comment by Klebestreifen** [comment]
Translation: I have this problem. Can someone help me to solve it?
I do not use Optifine!

**Comment by LatvianModder** [comment]
Seems to be the same issue as https://github.com/FTBTeam/FTB-Quests/issues/145 hmmmm
