### ISSUE TITLE
Suggestions / Problem

### ISSUE THREAD

**Issue by vkub4plv** [FTBTeam/FTB-Quests#245]
Hi there, so I've been using this mod for a while and I've decided to come here so maybe you could have improve it (At the beginning I would like to point out, that I don't speak English too well, so I apologize in advance for any future mistakes) 
So first and most problematic thing is that, that I've been makings some quests (about 1000) and everything seemed to work properly, of course, a lot of dependencies in one tree (about 75 quest per tree and usually, every quest with at least one dependention and usually at least one from another tree), but when I had all my 1000 quests done and I've started to test them and then when I had about half of my quests done my game started lagging a lot when I was in my eq and when I set them to be completed when I tried to open my eq my game got stuck and I couldn't have done anything more than close it and the only solution to open my eq again was to reset quests. Then I've deleted all dependencies and completed them and there were no problems then I've set dependencies only on separated trees, not including any other trees in them and they worked fine, but when I've set some dependencies on first quests of trees to require the previous one only to the first half on trees and I've completed them, but my game lagged a lot, hope there is something you can do to solve this problem, or I will have to handle without it.
So coming to the suggestions - things I would have like to see:
- Option to hide quest / tree until at least one / all of the quests from its dependencies is complete
- Option to copy quests / trees / move quests between trees / copy quests from one tree to another
- Set dependencies to multiple quests (from the one in tree and from the one available from the edition mode) / move multiple quests at once / 
- Option to set a reward for completing specific tree / all trees
Hope to see something of it in the future if possible.

**Comment by Slowwloriss** [comment]
You can hide quests with visibility option. If you have a invisible quest inside a chapter, the chapter will be invisible until the quest is visible. You can set Dependency Requirement on "all completed/started" "one completed/started". Quests can be dependents of a chapter. You can do a quest with tree requirement with Reward.

**Comment by LatvianModder** [comment]
Quest hiding is implemented, chapter rewards have been suggested here https://github.com/FTBTeam/FTB-Quests/issues/124
