### ISSUE TITLE
Sometimes you can't click things until you reopen the menu

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#252]
Maybe an extension of #202, but it might be something unrelated.

Specifically the one that's repeatable right now is when you're looking at the reward tables, click on any of them and then click either of the first two buttons (Hide Tooltip or Use Title). It does the same invisible context menu that #202 has and you can't click anything until you close out and reopen the menu.

**Comment by LatvianModder** [comment]
Gonna close this because editor soon + similar to old ones
