### ISSUE TITLE
You should be able to give more than a stack of an item in a single reward

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#254]
Say, giving 2 stacks of Cobblestone without having to make 2 tasks of a stack each.

**Comment by MaxNeedsSnacks** [comment]
I feel like this ties in with https://github.com/FTBTeam/FTB-Quests/issues/176, honestly, a List of Rewards would make this pretty much trivial, but of course, it'd also be nice to be able to clump >64 items into one reward without making a table, I agree with you on that

**Comment by LatvianModder** [comment]
Yeah, this will be part of grouped rewards
