### ISSUE TITLE
When opening FTB Quest book, it shows a black/ blue screen and only top right corner is seen. 

### ISSUE THREAD

**Issue by JazzWithJason** [FTBTeam/FTB-Quests#259]
Please fix this as i cannot do anything. This issue was experienced by me in Stoneblock 2 as well as Odyssey. Both of them are the latest versions. When the black screen appears, i have no other option than to kill minecraft, then start again. Please fix this. I have seen 2 other posts but it seems to be that no one cares. 
![image](https://user-images.githubusercontent.com/50610458/57673739-ae8a7100-763a-11e9-8178-d33bd46198ee.png)

**Comment by JazzWithJason** [comment]
Turns out, if i click the shop button, i can get out of it, But i still cant see quests

**Comment by LatvianModder** [comment]
Hmmm.. same issue as https://github.com/FTBTeam/FTB-Quests/issues/145 What's your GPU?
