### ISSUE TITLE
If an Item Task has an Item Filter but also has anything else in the same item list, it will cycle between those items and the Item Filter instead of the items in the Item Filter

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#263]
Extremely wordy title, but it cycles between these:
![image](https://user-images.githubusercontent.com/15698722/57988865-c312a300-7a58-11e9-901c-8ed3437a196e.png)
![image](https://user-images.githubusercontent.com/15698722/57988869-c73ec080-7a58-11e9-8498-21df0e004a6a.png)
instead of cycling between everything in the Item Filter and then everything else in the item list.

**Comment by LatvianModder** [comment]
You can't do that, filter only works if its the only item in list
