### ISSUE TITLE
If you set a chapter's group as an already-existing subchapter, it doesn't show up until you make the subchapter a regular chapter

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#272]
![image](https://user-images.githubusercontent.com/15698722/58436218-d1c90d80-8089-11e9-8aaa-71b9d9b900de.png)
The storage chapter has these subchapters. If I set another chapter to be a subchapter of Refined Storage - Expert, it disappears off the list.
![image](https://user-images.githubusercontent.com/15698722/58436233-eefddc00-8089-11e9-8f72-d4bdab976dec.png)
If I set RS-Expert to not be in a group, I can see the subchaper again.
![image](https://user-images.githubusercontent.com/15698722/58436249-08068d00-808a-11e9-81bb-4763d9ef646b.png)

Either subchapters shouldn't show be able to be selected as a group (and also, can't change the group of a quest that already has subchapters from None), or there should be subsubchapters (and subsubsubchapters, and subsubsubsubchapters, etc).

**Comment by LatvianModder** [comment]
You shouldnt select subchapters are groups, but I haven't added filter for that yet

**Comment by MaxNeedsSnacks** [comment]
No longer applicable
