### ISSUE TITLE
Moving quests with subchapters renders incorrectly

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#273]
![image](https://user-images.githubusercontent.com/15698722/58436479-2d47cb00-808b-11e9-9f68-595d89b10d4b.png)
Move it one up
![image](https://user-images.githubusercontent.com/15698722/58436482-38026000-808b-11e9-8694-b94552dc4c2c.png)
Click away
![image](https://user-images.githubusercontent.com/15698722/58436489-3fc20480-808b-11e9-892b-1d9909816926.png)

**Comment by LatvianModder** [comment]
Right now nothing I can do about this until the editor is added

**Comment by MaxNeedsSnacks** [comment]
No longer applicable
