### ISSUE TITLE
[Feature Req] (Bulk) Move Selected Quests to another chapter

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Quests#275]
With the new FTBQ update, I feel like a lot of packs might try to change up their quest structure (I know for certain I will eventually) and move quests that were previously just grouped together into different subchapters under the same top-level chapter.

A "Move" or even "Bulk Move" feature for when you have quests selected would be *really* helpful in getting those two tasks done a lot quicker, plus it would add to the (currently rather empty) context menu on multi-quest selections.

**Comment by LatvianModder** [comment]
Tbh I kinda forgot to implement it, I was gonna for this version

**Comment by ViridianFire** [comment]
Sorry for the necro but was this ever implemented? I've been wanting to bulk-move some of my quests into a new chapter
