### ISSUE TITLE
Context menu is cluttered

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#277]
![image](https://user-images.githubusercontent.com/15698722/58438559-13ab8100-8095-11e9-9d0f-cc3e91cbf014.png)
Some of these, like `Hide Text Until Quest is Completed` should only be in the edit menu I think. Maybe `Dependancy Requirement` and `Tasks Ignore Dependencies` too

**Comment by LatvianModder** [comment]
https://github.com/FTBTeam/FTB-Quests/issues/278
