### ISSUE TITLE
[Suggestion] Reward box shouldn't be present when quest doesnt have reward.

### ISSUE THREAD

**Issue by Slowwloriss** [FTBTeam/FTB-Quests#281]
When the quest doesnt have reward, the reward box should not be present, leaving all the space to Tasks. Only Stetic thing.

**Comment by LatvianModder** [comment]
I wanted to do that, but it would look a bit weird. Plus tasks no longer take a lot of space anyway and I add the "No Rewards" text, so people know its not a bug
