### ISSUE TITLE
Item counts should show on the task list

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#283]
![image](https://user-images.githubusercontent.com/15698722/58450164-5f7d1b00-80d3-11e9-9101-1b12ebd48cd3.png)

Instead of having to hover over it, it should just have a small 8 in the corner, like if it were in your inventory.

**Comment by LatvianModder** [comment]
But what if its 1000000

**Comment by Ethryan** [comment]
Perhaps you can use alphabetics to indicate large numbers.

**Comment by MaxNeedsSnacks** [comment]
I was about to say, as long as it fits, the shorthand notation should be fair game

1536 becomes 1.5K
and a googol becomes 1.0E100
