### ISSUE TITLE
When there's more chapters than fits in screen, the selection box's Y is off

### ISSUE THREAD

**Issue by raziel23x** [FTBTeam/FTB-Quests#290]
all of a sudden
![image](https://user-images.githubusercontent.com/441966/58776280-dfa1f580-8597-11e9-9a54-ed1f06531af4.png)
 my GUI moved to the right and left of my clients instead of being across the top how can i fix this as i cannot find any setting to edit the layout of the quest gui

**Comment by MaxNeedsSnacks** [comment]
That's just the new layout of the Quest GUI, I'm assuming it's to make things a bit more Content creator friendly (that being said, being able to set this in your settings would be kind of a neat idea if it weren't for subchapters)

**Comment by raziel23x** [comment]
the problem is when i scroll to the bottom of list of quest they glitch out  and the tab will move out of range of my cursor and when i go to highlight it after it moves on the screen the tab will vanish and i end up having to spam tab key to cycle through them
