### ISSUE TITLE
"Random Bonus" should be reflected in Reward section somehow

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Quests#291]
Say I had a quest that gave some random amount of gunpowder between 2x and 8x, like this:

![image](https://user-images.githubusercontent.com/12750501/58808918-3d2b5600-861b-11e9-9c03-b5d7683ca805.png)

Currently, the GUI only displays the minimum amount you can get from the reward (aka 2x). I think one good way to handle this would be to just cycle through the different reward sizes on the icon, such that it would show 2->3->4->...->8->2.

While we're on the topic of the Quest Reward section, I just noticed within the same quest that my custom title isn't being applied when hovering over the reward, as soon below.

![image](https://user-images.githubusercontent.com/12750501/58809096-91ced100-861b-11e9-9299-ed043dd24193.png)

![image](https://user-images.githubusercontent.com/12750501/58809117-9b583900-861b-11e9-99ff-8c62026e3d9f.png)

I don't know what might be the cause here, but it probably doesn't work for any item rewards, I would assume

**Comment by LatvianModder** [comment]
It used to be like that before I rewrote UI, I will bring that back

**Comment by MaxNeedsSnacks** [comment]
Thanks a bunch! I just noticed something (kind of) minor, apparently the reward now shows "6-8" which is incorrect, the base amount is 2, the random bonus is 6 ^^


![image](https://user-images.githubusercontent.com/12750501/59964404-66dfea80-9500-11e9-87a3-7dd213217587.png)

also, apparently, the custom name still doesn't seem to be working, I'm guessing that's because you're showing the item tooltip directly(?)
