### ISSUE TITLE
Add back "Unlocked by" and "Unlocks" in selected quest menu

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#296]
This is especially useful for quests that unlock quests in other chapters, so you can see what quests you can do now

**Comment by Timeslice42** [comment]
I was looking for the config setting for this. Why was this information removed?

**Comment by aaronhowser1** [comment]
There was an entire UI redesign. I did make a mockup of how this could fit in with the new design though:
![](https://cdn.discordapp.com/attachments/303440391124942858/623505329346576392/unknown.png)
