### ISSUE TITLE
Reward count disappears after being claimed

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#298]
![image](https://user-images.githubusercontent.com/15698722/59297382-c5c67980-8c4d-11e9-8029-942750eaf90d.png)
![image](https://user-images.githubusercontent.com/15698722/59297386-c8c16a00-8c4d-11e9-8108-f7770c4626c5.png)
Not majorly important but I feel like it should stay there after

**Comment by LatvianModder** [comment]
Not a bug, this is intentional
