### ISSUE TITLE
Reward Table item count doesn't update unless you click accept and then reopen the table

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#300]
Literally just #234 
![image](https://user-images.githubusercontent.com/15698722/59297910-fbb82d80-8c4e-11e9-9d38-211ba03406bb.png)
![image](https://user-images.githubusercontent.com/15698722/59297918-007ce180-8c4f-11e9-9d0e-a0fc7178132a.png)

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue
