### ISSUE TITLE
Add Reverse Dependency

### ISSUE THREAD

**Issue by MinerBryan** [FTBTeam/FTB-Quests#302]
Basically lock quests after a quest has been completed. Not much to explain. Perhaps an example would be nice?

'The Bones Quest' can buy 1 bone for 20 FTB Money coins. If the Mob_grinding_utils mod quest is completed, 'The Bones Quest' is locked and another quest opens, this new quests buys 1 bone for 10 FTB Money coins.

**Comment by RobinNightWing** [comment]
this would be very cool.

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #265
