### ISSUE TITLE
[Suggestion] Cooldown on repeatable quests and ability to completely hide quests.

### ISSUE THREAD

**Issue by OrionAF** [FTBTeam/FTB-Quests#303]
Give us an option to make a quest repeatable but on a cooldown.  Good for servers who want to have daily/weekly/monthly quests.  

Also to be able to completely hide quests, so they can only be seen in edit mode.

**Comment by pyure** [comment]
Duplicate of #72

**Comment by MaxNeedsSnacks** [comment]
As already stated by pyure: This is a duplicate of #72
