### ISSUE TITLE
weirdness with more than a stack of a single item as a task

### ISSUE THREAD

**Issue by MasterSloth1** [FTBTeam/FTB-Quests#323]
(not a great title but idk how to explain it lol)
so i made a quest that requires the player to get 114 grout if the player has 0 on them and picks up/gets 64 grout and then gets the remaining 50 the quest doesn't detect as complete but if the player has 0 on them then picks up 50 grout and then the remaining 64 it detects and completes the quest.

currently using = 
minecraft 1.12
forge-14.23.5.2838
FTBLib-5.4.3.129
FTBQuests-1.7.2.187
FTBUtilities-5.4.0.100

**Comment by LatvianModder** [comment]
It works just like advancements. Completion number is max of items you have in inventory. If its stack, it will be 64, if its 2 stacks, it will become 128

**Comment by MasterSloth1** [comment]
yes i have 64 and 50 in my inventory and it still doesnt detect
but if i have 50 in my inv then pick up 64 it completes
but if i have 64 then pick up 50 it doesnt

**Comment by MasterSloth1** [comment]
https://youtu.be/qvOHV5lsIPs

**Comment by josiah-roberts** [comment]
Plus one - having this issue on Infitech 3
