### ISSUE TITLE
Item Lists: Item Filter (OreDict) doesn't work in conjunction with ItemStacks

### ISSUE THREAD

**Issue by pyure** [FTBTeam/FTB-Quests#332]
Heya Latvian
* Edit an Item List
* Add Iron Ingot (vanilla)
* Add another item.  Use an Item Filter with "dustIron"

I would expect either an Iron Ingot or an Iron Dust to qualify for this quest, but the dustIron is ignored.

The Iron ingot triggers it properly.  dustIron suddenly works if its all alone in the list (you remove the Iron Ingot.)

**FTBQuests-1.7.2.189.jar**

**Comment by MaxNeedsSnacks** [comment]
Fixed by #447
