### ISSUE TITLE
FTB Quest 1.7.2.192 Custom NPC Integration addon and the think of Quest begin and Quest end

### ISSUE THREAD

**Issue by Titoo8899** [FTBTeam/FTB-Quests#334]
Hi,
the new Update and the Custom NPC Integration is okay with Quest, Dialog etc. But I have one little think what you must add in the next time. The Custom NPC Quest Task in your mod can we only make then we begin a quest or talk with a Custom NPC. But we can not the task so make then we have finish a task of a NPC, when we become in the Quest Book a report your Quest ... is Finish get now your price of 100 Gold etc. Please add this what we can not only a task start quest make with the NPC Integration but also then we a Task of a NPC ending a quest in your book can create that end then we have a task of NPC finish. Different have your NPC Integration not the function of this what I have hope of your mod. 

I hope you make this and in one of the next update, can we make Quest in your book what then end we have a task of a NPC of the Custom NPC mod finish then the task in your book.

**Comment by LatvianModder** [comment]
#343
