### ISSUE TITLE
Issues with LAN players

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#335]
Copied from FTBTeam/FTB-Academy/issues/45

* **Modpack Version**: 1.0.0

* **Issue**: A friend who is joining me on LAN who has already played will occasionally join and the game will act like they have never joined before. This causes them to lose their entire inventory and to reset our game progress to back at the academy.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/76e7c76f

* **Is it Repeatable?**: It has happened 3 times now but I am unsure of the cause.

* **Mod/s Affected**: Questing mod?

* **Known Fix**: Nothing. The game seems to read the other player as a new user. We have had to restart 3 times and we are not wanting to start again.

**Comment by Barberfluids** [comment]
I had a similar situation today.  Whether I host an FTB academy based world or my son on the LAN, and you join that server; it makes you go through FTB academy and then it hangs there and you can't get out and join the world that is being served.  Even if you follow the Academy steps, (without soft stopping with the known bug with the wooden chest).  Any way to bypass the Academy first step so I can join the world.  I tried quitting FTB Academy on the top left icon, that does nothing.

**Comment by Barberfluids** [comment]
It gets weirder too.  When I host the world, FTB utilities doesn't come up at all so you cannot claim chunks as a new player and you cannot break any blocks at all; even if you are away from Spawn and Spawn settings in the config file are set to zero.  Looks like we are moving onto another mod pack set.  It's too bad I love this modpack; just got to draconic power too.

**Comment by Barberfluids** [comment]
I don't know if this helps.  The issue exists whether we download the pack and install files individually and configure or copy the files for FTB from my computer onto his.
