### ISSUE TITLE
[Bug/Feature] Quests not detecting when not yet active

### ISSUE THREAD

**Issue by scribbler957** [FTBTeam/FTB-Quests#342]
When I complete quests before they're highlighted the mod isn't detecting them. For example, in the Antimatter Chemistry modpack, I had several stacks of dusty bones, used them and then unlocked the quest to collect a stack of them, incomplete. Sometimes this happens with rare or expensive items that a player might make/use in the process of fulfilling earlier quests. I think this also happened with quests to kill mobs I already killed.

**Comment by LatvianModder** [comment]
That's how it's supposed to work. Quests that are not yet available wont be detected. I could maybe add an option to detect items even if its not yet available, but that wouldnt be the default and would be up to modpack author

**Comment by scribbler957** [comment]
The thing is that in more than one modpack, and with more than one quest mod, I've done something like kill the dragon, or crafted something expensive and annoying that I don't need two of, only to open the quest later.

**Comment by mellamokb** [comment]
+1 on this.  For kitchen sink packs like MC Eternal with 750+ quests and 10s of unrelated quest lines, it makes you have to plan to follow the exact quest line which is IMO annoying and unfun.  It would be less tedious if later quests you already did were marked complete as soon as they activated.  Instead you go around your base breaking machines (and having to reset NBT in case of EnderIO) and picking out items from your storage system just to trigger the quest completion you already did.

IIRC the HQM and maybe BetterQuesting would track unavailable quests and mark them complete as soon as they became available.  I understand it is probably exponentially more work in the code to track everything, but I would give my agreement to implementing this.

Thanks! :)

**Comment by MaxNeedsSnacks** [comment]
I **think** this has been implemented with the "Tasks Ignore Dependencies" feature?
Feel free to reopen if this is still an issue

**Comment by MaxNeedsSnacks** [comment]
I **think** this has been implemented with the "Tasks Ignore Dependencies" feature?
Feel free to reopen if this is still an issue
