### ISSUE TITLE
[ Compatibility ] Research Table and Reskillable integration

### ISSUE THREAD

**Issue by ghreps** [FTBTeam/FTB-Quests#344]
Pls add compatibility with cool mods [Research Table](https://www.curseforge.com/minecraft/mc-mods/research-table) and [Reskillable](https://www.curseforge.com/minecraft/mc-mods/reskillable)

This mods already have compat with Game Stages

**Comment by LatvianModder** [comment]
Couldn't you just use gamestage rewards/tasks then?

**Comment by MaxNeedsSnacks** [comment]
Partially fixed by #431
