### ISSUE TITLE
FTB Money rewards can't be auto-claimed

### ISSUE THREAD

**Issue by al132mc** [FTBTeam/FTB-Quests#346]
Pretty self explanatory I hope. Item auto-claiming seems to work, and intuitively i'd think that money auto-claiming would be easier to implement because you don't need to worry about fitting it in an inventory.

**Comment by CygnusInfinity** [comment]
Just gonna bump this because it would make life a lot easier for me in the pack I'm currently playing

**Comment by sithrebel15** [comment]
+1 possible as a option that can be enabled/disabled by the pack creators.

**Comment by MaxNeedsSnacks** [comment]
See https://github.com/FTBTeam/FTB-Quests/issues/388#issuecomment-778377897
