### ISSUE TITLE
Pin is almost unreadable on Gui scale: Normal

### ISSUE THREAD

**Issue by JoachimFlottorp** [FTBTeam/FTB-Quests#348]
Pinned quests are unreadeble on Gui scale: Normal.
Resolution 

You should the ability to make it bigger. or make it automatically bigger with the gui scale setting.

![e3ce256d4b626e959ab4989c522690ca](https://user-images.githubusercontent.com/24413121/65248851-27bb3880-daf3-11e9-80e2-906353714a06.png)

**Comment by SSmale** [comment]
+1 also having this issue. I have a 2k screen so have the GUI set for that and it is comfortable to read and the pinned quest text is so much smaller. it would be nice to be able to scale it in the settings

**Comment by LatvianModder** [comment]
I added theme property for that. You can now tweak it by making `resources/ftbquests/ftb_quests_theme.txt` file and adding

```
[*]
pinned_quest_size: 0.75
```

to it. You can change it to any value, default being 0.75
