### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by uncureablebos56** [FTBTeam/FTB-Quests#349]
I was looking for a new mod pack and found rouge-like adventures and dungeons and it looked perfect from the description.

I went to look at the quest book but instead of opening, upon clicking i immediately crash and get this report.

https://paste.dimdev.org/upifayudor.mccrash

**Comment by Gunner76th** [comment]
@LatvianModder I see you closed this, can you explain the cause of this crash, and possibly how Server administrators can resolve it please?

**Comment by LatvianModder** [comment]
Most issues I closed because they have already been resolved/fixed. If this is still a thing, reopen it
