### ISSUE TITLE
Limitless quest page size

### ISSUE THREAD

**Issue by TimGoll** [FTBTeam/FTB-Quests#35]
Add a config option to enable bigger areas to add quests.

![image](https://user-images.githubusercontent.com/13639408/45597760-1962aa00-b9d1-11e8-822d-4d4c06dcaece.png)

The area is quite small

**Comment by TimGoll** [comment]
If you give me a hint where you initialize the grid I can change this by myself and open a PR

**Comment by LatvianModder** [comment]
I can easily make it larger if I want to, its a constant in Quest.java, POS_LIMIT. But I want to make bigger change first so I can have infinitely large quest pages, so this will have to wait a bit. Placing quests next to each other, would give you 2x more space. Recent update added a small gap between them, so it doesn't look bad anymore

**Comment by TimGoll** [comment]
Thanks. Yes, changing to a smaller gap and using the y direction would allow me to add way more quests. This would be my compromise solution. 
I'd like to release my modpack in a month or so. Do you think you have made your other change until then?

**Comment by LatvianModder** [comment]
Most likely yes

**Comment by thetakodev** [comment]
Now imagine, some modpack features the last quest, and to open it you have to scroll through the quest GUI for an hour.

**Comment by TimGoll** [comment]
Yes. Therefore I've switched to multiple "chapters"
