### ISSUE TITLE
interation script not working 

### ISSUE THREAD

**Issue by mitchngwen** [FTBTeam/FTB-Quests#359]
This script is not working

```js
events.listen("block.left_click", function(event) {
   if(event.server && event.block.id.equals("minecraft:log")) { //Replace withh block ID
     event.player.data.ftbquests.addProgress("a6a42e18", 1); //Create Custom Task and copy it's ID
   }
});
```

**Comment by LatvianModder** [comment]
For future references, you can use 3x ` and language name for custom formatting :P

\`\`\`js
var a = 10
\`\`\`

![image](https://user-images.githubusercontent.com/3844385/67700074-f36e4e00-f9b5-11e9-8b63-363354ed10e9.png)

Are you sure you copied the **Task** ID not Quest ID? It works for me

**Comment by LatvianModder** [comment]
I can see how getting item from block can be useful, so I have added `event.block.item` in newest update. You can now use `if(event.server && ingredient.of("ore:logWood").test(event.block.item)) {`

https://jenkins.latmod.com/job/KubeJS/55/

**Comment by mitchngwen** [comment]
I got it to work had something to do with the server not syncing I guess. You are very helpful and not stuck up like some of these other coders, I appreciate that. Awesome add on BTW it's perfect for the quest I wanted.
