### ISSUE TITLE
Crash w/ Warp Drive

### ISSUE THREAD

**Issue by AnimalLover567** [FTBTeam/FTB-Quests#360]
Upon loading minecraft crashes with a java.lang.NullPointerException, i've reported said crash to mod author of warp drive and he's in the process of fixing it, he says "That's an ftbquests bug, causing NPE when asked for block's hardness." [here](https://pastebin.com/MfJQb4Wv) is the crashlog.

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, if the issue with this mod still persists on 1.16+, feel free to reopen ^^
