### ISSUE TITLE
propose

### ISSUE THREAD

**Issue by axin0452** [FTBTeam/FTB-Quests#362]
Can you add a cool down time for repetitive tasks？

**Comment by pyure** [comment]
Seconded.  But please, dude, use an actual descriptive title.  It was hard to find this before I duplicated the same request.

**Comment by pyure** [comment]
Duplicate of #303

**Comment by pyure** [comment]
Duplicate of #72

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #72
