### ISSUE TITLE
Grid Thing Appearing in Editing Mode

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Quests#363]
I don't know what this thing is or how to disable it, but it's annoying af.

Why does it have a grid-selector thing on the mouse cursor?

![2019-11-14_19 38 36](https://user-images.githubusercontent.com/31721920/68998095-69f2c300-0873-11ea-8fbb-1cc2165cfa91.png)

**Comment by LatvianModder** [comment]
Press R key to toggle it
