### ISSUE TITLE
Can't hit R to view item recipes, shows ruler instead

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#366]
![image](https://user-images.githubusercontent.com/15698722/70231574-368faf80-1720-11ea-97c3-1bd44a72abfb.png)

**Comment by MaxNeedsSnacks** [comment]
For 1.12: This is only a thing in editing mode
For 1.16: JEI integration doesn't exist yet iirc, but it'll be coming back in a future release.
