### ISSUE TITLE
Question: Do you know a way to use PSI Spell Nodes in Quests?

### ISSUE THREAD

**Issue by Tylerun** [FTBTeam/FTB-Quests#370]
A couple of friends and I want to make it so that a certain spell "Trick:Infusion" That only has trick infusion in it is what completes the quest. We got the first quest to work but when we try to do another quest labeled "Trick:Greater Infusion" It gets completed for having the original in your inventory. Do you know of a way NBT wised to make it so this does not happen. I tried Matching NBT and it still completed. Any info would be greatly appreciated.

**Comment by MaxNeedsSnacks** [comment]
That would need custom mod integration on Psi's end as Spell Nodes aren't physical items; using bullets isn't feasible because you'd have to use the **exact** spell setup demanded by the quest.

Either way, this won't be worked on for 1.12 as that version is unsupported, unfortunately
