### ISSUE TITLE
Cannot Set Stat Value to 0

### ISSUE THREAD

**Issue by GamerBah** [FTBTeam/FTB-Quests#375]
Stat Quest values are locked at a minimum of 1, which makes it impossible to make a quest for having 0 deaths after a certain amount of time played.

**Comment by MaxNeedsSnacks** [comment]
You could try to achieve this using KubeJS custom tasks, as quests aren't meant to be "uncompletable" and Stat tasks accept any stat value **higher** than their requirement, meaning that if we lowered the limit to 0 that task would automatically complete
