### ISSUE TITLE
hide information lost when starting the map [1.15]

### ISSUE THREAD

**Issue by Djimon** [FTBTeam/FTB-Quests#379]
I tried several times to make sure what the issue is.
when i create my quests i use hide quest and hide depedencie lines.
I monitored the .snbt files in the config folder and made several observations.
 1. it seems as if the quests are saved only after a certain time period. So when I add sth in the quest and save&quit the changes may not be inlcuded [Suggestion]-> real save button (not save to file)
 2. it occurs randomly that a single chapter (.snbt) isn't updated any more. (when often closing and restarting minecraft) You cannot work on this chapter. it won't create a new or similar file in config. the chapter's changes will jsut be ignored. Only solution i found: delete and create new :(
 3. and th main issue: during creation everything is saved correctly  
      -  hide_dependency_lines: 1,
      -  hide: 1,
when I close MC and reload my map, the quests are initially loaded without any hide flags. and after   a certain amount of time (see 1.) the quests in my config folder are overwritten (no more hide_dependenciy_lines, no more hide) :/

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in 1.16+ versions of Quests anymore, hopefully, if it is, feel free to reopen!
