### ISSUE TITLE
Crash when oppening ftb quest gui.

### ISSUE THREAD

**Issue by Mrthomas20121** [FTBTeam/FTB-Quests#381]
it crash every times i try to open ftb quest gui via the inventory. 
crash report : https://paste.dimdev.org/ibaveqirof.mccrash

ftb quest version : 1.8.0.237
 ftb lib version : 5.4.5.1

**Comment by Mrthomas20121** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Quests/files/4261606/latest.log)
Added latest.log

**Comment by lamoyrl90** [comment]
Same, both on hotkey and using the book:

https://paste.dimdev.org/oxafutuneq.mccrash
https://paste.dimdev.org/ozatiyulec.mccrash

Tried updating FTB Lib, will see if that works.

**Comment by lamoyrl90** [comment]
Updating FTB Library resolved the issue.
