### ISSUE TITLE
Quest Chest spam

### ISSUE THREAD

**Issue by scribbler957** [FTBTeam/FTB-Quests#382]
FTB Quests 1.8.0.237, MC.Eternal Modpack 1.3.4, MC 1.12.2

I had items being piped into quest chests and I would occasionally "collect all." I just updated my pack and I was flooded with an endless parade of toasts and my inventory started filling with coins. I tried breaking and replacing the chests, but it didn't stop.

I can't even find the control for auto-submit. It seems kind of unplayable in this condition.

**Comment by scribbler957** [comment]
I've been told that this is because of how adam set up the quests in MCE. I'll leave this for the FTB Team to close if it's helpful.

**Comment by MaxNeedsSnacks** [comment]
As stated in https://github.com/FTBTeam/FTB-Quests/issues/504#issuecomment-778333959, Quest chests are.. pretty terrible, and will hopefully be reworked for future versions as 1.12 is unsupported now
