### ISSUE TITLE
On the wiki, the Reward Table page is a broken link 

### ISSUE THREAD

**Issue by bikinavisho** [FTBTeam/FTB-Quests#383]
When you go to the [Loot Crates](https://github.com/FTBTeam/FTB-Quests/wiki/Loot-Crates) page and try to click the Reward Table link, it brings you back to the home page of the wiki.

**Comment by MaxNeedsSnacks** [comment]
@LatvianModder mind giving me a refresher on where our docs for the FTB Suite are actually stored now?

**Comment by MaxNeedsSnacks** [comment]
Our documentation is currently a little sparse still unfortunately (we're working on it though!), but you can currently find all of the relevant mod docs at https://feedthebeast.notion.site/FTB-Mod-Documentation-da2e359bad2449459d58d787edda3168
