### ISSUE TITLE
Question Really about the ui

### ISSUE THREAD

**Issue by TheRandomCrafter83** [FTBTeam/FTB-Quests#384]
I may be blind as a bat, but I want to ask this question anyway. In StoneBlock 2, i noticed that the task chapters appear along the top edge of the quest book. How can I go about replicating this for a mod pack?

**Comment by MaxNeedsSnacks** [comment]
That was the ***old*** chapter layout, which we ditched because it was too clunky and unclear to the user.
Unfortunately, there's no way to replicate it, and we probably won't be moving in that direction anymore, either
