### ISSUE TITLE
Endless rewards bug on 1.12.2

### ISSUE THREAD

**Issue by runescapejon** [FTBTeam/FTB-Quests#385]
Version that i am currently running is
- FTB Quest 1.8.0.238
- Forge - 1.12.2 - 14.23.5.2847

My issue is any rewards are being executed more then once. You can even spam the rewards and it will let you have them more the once. Even if you have `can be repeated` = false It's a clear indication that this is the cause of the bug https://github.com/FTBTeam/FTB-Quests/commit/aa5233822676f54973150089b5836bccab52d350 Because i had roll back onto .237 and the issue was fixed. Here a few screenshot of a demonstration.

https://gyazo.com/1e0f32617baa79edde2ec92b3ee38c85

`Here how to reproduce`
1) obtain ftbquest book
2) grab an item use to in the quest (ex. stone)
3) Set the item into the quest book as a task. 
4) set the reward item you would like
5) complete the task that you set for step 3
6) just click spam the rewards and then you'll earn it more then once.

**Comment by gaminggirl** [comment]
Same for me on same versions of FTB Quests and Forge seems to be all quests and no matter if repeatable or not.

**Comment by LatvianModder** [comment]
Someone reported me this bug, I changed the file on CF to Alpha and added big warning in description but it didn't save 🤦‍♂ anyway, this will be fixed soon ™️

**Comment by DAmNRelentless** [comment]
> Someone reported me this bug, I changed the file on CF to Alpha and added big warning in description but it didn't save 🤦‍♂ anyway, this will be fixed soon ™️

Well, it's been a while.

**Comment by MaxNeedsSnacks** [comment]
IIRC this is
(a) irrelevant on 1.16 and
(b) was (most likely) fixed in a newer 1.12 release,
so I'll be closing this for now ^^
