### ISSUE TITLE
How would I give money for a kill? Auto Claim Not working

### ISSUE THREAD

**Issue by thewawpro** [FTBTeam/FTB-Quests#388]
I have a quest that when you kill a zombie you get $1 and the money is on auto-claim but it doesn't auto claim. Anyway to do this/is this intentional?

**Comment by MaxNeedsSnacks** [comment]
This is a bug with money rewards in 1.12, which is unfortunately an unsupported version.
I would generally recommend *against* using FTB Money together with Quests rewards in any meaningful quantity, as it's quite unfinished and has been discontinued for newer MC versions (will be part of FTB Quests eventually)
