### ISSUE TITLE
Repeatable Quests don't appear to be repeatable (Modpack Design)

### ISSUE THREAD

**Issue by 99Blocks** [FTBTeam/FTB-Quests#389]
Morning!

I'm currently trying out FTBQuests in creating a modpack for the first time and I am having some difficulty with getting repeatable quests to actually repeat. I feel this is probably my error but I wanted to check as I can't see anyone else having the same problems I am.

I have attached some screenshots of my current settings in game but the quest is only completed once before being marked as 100% and not resetting.

**Versions**
Minecraft 1.12.2
Forge 14.23.5.2847
FTB Library - 5.4.7.0.jar
FTB Quests - 1.8.0.238.jar

**Methods attempted:**
- New world
- Survival and Creative Mode
- Attempts to complete in both edit mode and regular mode
- Various combinations of left/right click
- Various combinations of quest data in config mode

**Screenshots**
Quest Settings - https://i.gyazo.com/771b475778d33ee5c07f8095807b9f2c.png
Chapter Settings - https://i.gyazo.com/a51f063d5955f539c183156a9271d167.png
Task Settings - https://i.gyazo.com/3119ab81881688de36c461201624e1d4.png
Reward Settings - https://i.gyazo.com/927938bf244b7e8a0bef6c30c6127ab0.png

_Appreciate any help (Even if it is just me being a moron and not setting it up properly!_

**Comment by LatvianModder** [comment]
Roll back to 237, 238 is bugged, its noted in changelog, will be fixed soon ™️

**Comment by 99Blocks** [comment]
Thanks for the swift response!

I could've saved myself a lot of time by reading the changelog...
Learned the hard way there. Keep up the great work :)
