### ISSUE TITLE
1.15 Crash with Dark utils Player Damage Trap

### ISSUE THREAD

**Issue by Darkere** [FTBTeam/FTB-Quests#390]
https://gist.github.com/Darkere/70c01f3af9b4272990f581aaf2d9d128

ftb-quests-2.0.2.244
forge 31.1.27

**Comment by Darkere** [comment]
https://github.com/FTBTeam/FTB-Quests/blob/66af5480e38b9c06f40cbf7cfa8df200880c9a0b/src/main/java/com/feed_the_beast/ftbquests/FTBQuestsEventHandler.java#L187

if (event.getSource().getTrueSource() instanceof ServerPlayerEntity && !(event.getSource().getTrueSource() instanceof FakePlayer))

:)

**Comment by mrdeadlocked** [comment]
I'm having the same issue. 👍

**Comment by noncom** [comment]
Same thing here

**Comment by noncom** [comment]
+1, same thing here

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in newer versions of Quests, hopefully, if it is, feel free to reopen!
