### ISSUE TITLE
1.15 NullPointer getting quest title 

### ISSUE THREAD

**Issue by Darkere** [FTBTeam/FTB-Quests#391]
Not sure if this is actually toast control or just an error with quests. 

https://gist.github.com/Darkere/2db5b9443be53915ba03e33f68cc0047

EDIT: Confirmed not an issue with toastcontrol
https://gist.github.com/Darkere/a5d93c64240e49403743d05c362a9365

ToastControl-1.15.2-3.0.1
ftb-quests-2.0.2.244

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in newer versions of Quests, hopefully, if it is, feel free to reopen!
