### ISSUE TITLE
[1.15.2] Wrong rendering

### ISSUE THREAD

**Issue by MelanX** [FTBTeam/FTB-Quests#394]
I saw a few rendering bugs with text boxes. And it's different in edit mode on/off

Edit mode on images:
![image](https://user-images.githubusercontent.com/26039509/78451720-9c1c8a00-7687-11ea-8a60-c478768cd549.png)
![image](https://user-images.githubusercontent.com/26039509/78451769-db4adb00-7687-11ea-8cd4-7d87eb91205c.png)
![image](https://user-images.githubusercontent.com/26039509/78451754-c5d5b100-7687-11ea-9302-99c530194a26.png)
![image](https://user-images.githubusercontent.com/26039509/78451757-cf5f1900-7687-11ea-89fe-98969772c77b.png) (for comparing)

Edit mode off images:
![image](https://user-images.githubusercontent.com/26039509/78451784-ee5dab00-7687-11ea-8fcd-b5de90e848eb.png)
![image](https://user-images.githubusercontent.com/26039509/78451799-fcabc700-7687-11ea-8934-11532b44e22a.png)

mod version: 2.0.2.244
forge: 31.1.35

**Comment by DArkHekRoMaNT** [comment]
Same problem
![FTBQuests_Render_Bug](https://user-images.githubusercontent.com/15899143/82232562-785f8b80-9937-11ea-876b-d3810b250ad3.jpg)

**Comment by Spongman** [comment]
I see the same issue in 'Craft to Exile [Dissonance]'

**Comment by diogoalexsmachado** [comment]
Any ETA on this yet? Been waiting for a few weeks now :(

**Comment by MaxNeedsSnacks** [comment]
As stated in #505, 1.15 is unsupported and won't be worked on anymore, sorry!
If a fix is backported, feel free to PR it in (or fork the mod, if Lat gives you permission to do so)
