### ISSUE TITLE
[1.15.2] Reward table creation broken

### ISSUE THREAD

**Issue by MelanX** [FTBTeam/FTB-Quests#395]
When you try to create a new reward table like this and press "accept", nothing happens on screen.
![image](https://user-images.githubusercontent.com/26039509/78452060-64aedd00-7689-11ea-8dc7-aa91baf6a188.png)
When you press Esc you will come back to normal gameplay. 
When going to Reward Tables, you see this:
![image](https://user-images.githubusercontent.com/26039509/78452173-ffa7b700-7689-11ea-8815-af3c8c4dd4d3.png)

You see: pressing accept results in 2 created reward tables. I just found out that pressing cancel creates 1 reward table and stuck in that creating screen, too.

mod version: 2.0.2.244
forge: 31.1.35

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue ^^
