### ISSUE TITLE
[1.15.2] Can't interact after changing value

### ISSUE THREAD

**Issue by MelanX** [FTBTeam/FTB-Quests#396]
Again, my favorite place... reward tables. If you change one of these values, you're not able to interact in that screen anymore. You need the press Esc (or close the game or shut down your PC in any way). 
![image](https://user-images.githubusercontent.com/26039509/78452364-2f0af380-768b-11ea-8db0-1b4fd0093adf.png)
mod version: 2.0.2.244
forge: 31.1.35

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue ^^
