### ISSUE TITLE
[1.15.2] Deleting is just hiding

### ISSUE THREAD

**Issue by MelanX** [FTBTeam/FTB-Quests#397]
I deleted a few reward tables. After restarting the game, the deleted tables are back.
![image](https://user-images.githubusercontent.com/26039509/78461257-a8283c00-76c7-11ea-9f4f-57fb30cf5e22.png)

mod version: 2.0.2.244
forge: 31.1.35

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue ^^
