### ISSUE TITLE
1.15 - Viewing an item's recipe crashes the game.

### ISSUE THREAD

**Issue by TwiiCe** [FTBTeam/FTB-Quests#398]
With or without editor mode on, the client crashes when viewing an item's recipe. (Clicking on it).

Here's the crashlog:
https://pastebin.com/9qkz9rgg

I've also reported this to the RandomPatches github, as I suspect this mod is part of the issue.

https://github.com/TheRandomLabs/RandomPatches/issues/86

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue on 1.16+ ^^
