### ISSUE TITLE
[1.15.2] Crash on left clicking a Quest

### ISSUE THREAD

**Issue by TheUntamed** [FTBTeam/FTB-Quests#399]
I created a checkmark-task-quest adn whenever I left-click it to open it my game crashes with the following crash report:

```
Description: Rendering screen

java.lang.NullPointerException: Property checkmark_task_inactive doesn't have a default value!
```

**Comment by TwiiCe** [comment]
I think this is related:
https://github.com/FTBTeam/FTB-Quests/issues/398

**Comment by TheUntamed** [comment]
Somehow. But I cannot even open the Quest (I can open the Quest window by pressing the book at the top left corner but not a single quest). Crash on viewing an item's recipe would imply that I can open a single quest,

**Comment by TheUntamed** [comment]
Further tests showed: The Crash on left clicking a quest only happens when it's a Checkmark quest. Other type of quests are fine.

**Comment by Naxanria** [comment]
Same issue. https://paste.feed-the-beast.com/view/9d8ac509

**Comment by PyroFlareX** [comment]
I can confirm on this. I get the same/similar crash for this.

**Comment by LatvianModder** [comment]
Should be fixed in https://jenkins.latmod.com/job/FTB-Quests/245/
