### ISSUE TITLE
[1.12.2] editing lag

### ISSUE THREAD

**Issue by thx114** [FTBTeam/FTB-Quests#400]
Every time I try to add a quest, modify the quest, there will be more than 5 seconds

Appears in the log after each pause：
I am not sure if there is a problem
“
[tfc]: World time and Calendar Time are out of sync! Trying to fix...
[tfc]: Calendar Time = 1169672 (11672), Player Time = 152434, World Time = 11678, doDaylightCycle = true, ArePlayersLoggedOn = true
[tfc]: Calendar is behind by 6 ticks, jumping calendar time to catch up
"

**Comment by MaxNeedsSnacks** [comment]
I'm... unsure how to fix this, if at all unfortunately, since I never encountered it on 1.12 myself, and since we've dropped support for that version anyways, I'll just have to close this issue for now, sorry :/
