### ISSUE TITLE
Shop not showing in different world

### ISSUE THREAD

**Issue by pyrossal** [FTBTeam/FTB-Quests#405]
I dont know why but i created a shop in a world everything is fine.
(a screenshot)
https://media.discordapp.net/attachments/700525355726798882/700611999465209938/Capture_decran_24.png?width=1204&height=677
but when i change world the shop disappear
(a screenshot)
https://media.discordapp.net/attachments/700525355726798882/700611970029715476/Capture_decran_23.png?width=1204&height=677

**Comment by MaxNeedsSnacks** [comment]
We'll be rewriting FTB Money for future versions, so this will hopefully not be an issue in future versions (if / when we release them)
