### ISSUE TITLE
Quests being reset upon the PC crashing

### ISSUE THREAD

**Issue by suduku189-New** [FTBTeam/FTB-Quests#407]
I have been playing a bit with the mod but when ever my PC crashes, they all get reset and i have to do them all again. Is there some command i can do to just give me them?

**Comment by MaxNeedsSnacks** [comment]
There are commands to force-complete quests which depend on the version (either way they need you to be an OP), but unfortunately, if your PC has crashed and the world didn't save, your quest progress is just gonna be gone for now, sorry :/
