### ISSUE TITLE
Completed quest progress stuck on the HUD

### ISSUE THREAD

**Issue by cimds** [FTBTeam/FTB-Quests#409]
I'm early in the pack MCEternal, and one of the first, already completed (and reward collected) quests has been stuck below the minimap on the side of the HUD for hours: "Crafting Table on a Stick 100%" It persists between restarting the game and changing worlds and I have no idea how to get rid of it. It may be caused by a time the game crashed for an unrelated reason.

**Comment by MaxNeedsSnacks** [comment]
You've probably pinned that quest ^^ To remove the pin, just click the little pin icon in the Quest's panel ^^
