### ISSUE TITLE
[1.12.2] Changing a subchapter's default shape closes the menu, so you have to navigate back to it

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#410]
![image](https://user-images.githubusercontent.com/15698722/81382905-c2917300-90d4-11ea-98d2-5ff6f02c961a.png)
![image](https://user-images.githubusercontent.com/15698722/81382919-c6bd9080-90d4-11ea-9ff9-6a3dfdb1de43.png)
fix it

**Comment by MaxNeedsSnacks** [comment]
Closing because we now have a new chapter format, which probably makes this issue invalid ^^
