### ISSUE TITLE
MCeternal issue

### ISSUE THREAD

**Issue by basti418** [FTBTeam/FTB-Quests#411]
So I posted this about 2 weeks ago on the actual page, and haven’t had any real fixes yet, I was referred here, maybe somebody here can help?    

I did all the logical steps, I deleted my extire MCeternal folder, did a fresh install on a completely different hard drive, new directory everything, I started a new world and here are a few pics to show you what i am having issues with, there are numerous more for this issue... the entire player shop section is the same for all items. I didn’t feel it was necessary to screen cap every single one, as it would have been completely redundant.  

I am unsure if I'm the only person with this issue as I cant find anything else online 

I will attach a google drive folder and drop box, just to be safe with all images included there are 16 photos.

https://drive.google.com/folderview?id=1w1dj7EhryTQzANJRHrahyxefVdgf2mn9

https://www.dropbox.com/sh/hemc6xo0qx2eigb/AACGz5YPLZLs1adb8maSgPrRa?dl=0

Thank You for any and all help :)

**Comment by MaxNeedsSnacks** [comment]
This sounds more like a pack-specific issue unfortunately, as you seem to be missing some mod whose items are being used in these quests, so (ignoring the fact this issue is >1 year old anyways) we can't really help you with it, sorry :/
