### ISSUE TITLE
MC Eternal 1.12.2 Coins Disappear 

### ISSUE THREAD

**Issue by BenNewland1** [FTBTeam/FTB-Quests#412]
There is a issue with the shop coin balance disappearing on a modpack M.C. Eternal which is using FTB quests 1.12.2

**Comment by BenNewland1** [comment]
Found the /pay username 1 command! LOL not sure if its still a issue really though?

**Comment by mortamure** [comment]
Happened to me also. A few days ago. Coins all gone. Completed quest have not changed.

**Comment by MaxNeedsSnacks** [comment]
FTB Money on 1.12 is... a bit of a mess, so we'll be rewriting it from scratch for future versions. Until then, not much I can really do to help since we've dropped support for 1.12 (and this issue is quite old anyways)
