### ISSUE TITLE
FTB Quests 1.15.2 crashes with Default Dimension mod

### ISSUE THREAD

**Issue by benserwa** [FTBTeam/FTB-Quests#413]
Crash: https://pastebin.com/1pekZLrp

latest.log: https://gist.github.com/benserwa/7e9b7136bbc12dc9d34e78a273e7af3d

**Comment by MaxNeedsSnacks** [comment]
Hopefully shouldn't be an issue in newer versions of Quests, but 1.15 is unfortunately unsupported, anyways.
