### ISSUE TITLE
quest issue

### ISSUE THREAD

**Issue by drjj97** [FTBTeam/FTB-Quests#416]
im playing pixelmon plus and there is a quest thats fairly endgame of making 100,000 pokeballs and putting them into a yabba barrel with the iron gold and diamond upgrades so i did that and its not turning in is there a way to just over ride it and set it as completed?

**Comment by MaxNeedsSnacks** [comment]
You can use /ftbquests change_progress to force complete that quest, but either way, 1.12 is unsupported
