### ISSUE TITLE
[HELP] Repeat quests on the server

### ISSUE THREAD

**Issue by JeanShamayin** [FTBTeam/FTB-Quests#418]
I would like to make some specific quests reset, so you can do them several times on my server (play with friends)

https://prnt.sc/svaado -- Those are the ones I wanted to do you can repeat

Is there a command or quest to reset another one? Or any other way to make it happen

P.S: I'm sorry for the bad English, I'm Brazilian, but I love your mods, I always use them on my servers!

**Comment by MaxNeedsSnacks** [comment]
Repeat quests have been a *pain* to reimplement in recent versions since we want to do them properly but can't really find the time to actually work on them, but they'll hopefully be back **very** soon (also sorry for the necro, going through old issues to find what's left to do)
