### ISSUE TITLE
[1.12.2] Quest Duplication Bug

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Quests#420]
Title. Quests randomly get duplicated.

The duplicates either replace the items with random ones, or are missing parts. If I delete a duplicated quest, it deletes the quest it was originally based on (ie a quest I have caled "Your First $50!" keeps duplicating itself)

It's more of a minor irritation (since the quests work fine other than having a weird duplicated "ghost"), but it's still rather irksome as I can't move or delete the duplicates

**Comment by MaxNeedsSnacks** [comment]
This should be fixed in the final 1.12 release we've made(?)
