### ISSUE TITLE
[1.15.2] Invisible Tooltips & icons overlapping Quest names.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Quests#421]
Tooltips show up while in editing mode but not while outside of editing mode.

Previews:
![FTBQ2](https://user-images.githubusercontent.com/26634554/84602392-577f4d00-ae87-11ea-8a31-7a3d4f2cf71e.png)

![FTBQ1](https://user-images.githubusercontent.com/26634554/84602395-59e1a700-ae87-11ea-8af2-b62187c1e5e9.PNG)

Can't read some of the Quest names due to the icon behind it overlapping it somehow. Only happens to a quest that has a dependency and is "grey".

**FTB Quests Version**: 2.0.2.246
**MC Version**: 1.15.2
**Forge Version**: 31.2.9

Sorry if this has already been reported. I've also heard that the mod is getting a rewrite. Is there an ETA? 
Thanks for the mod.
- Gbergz

**Comment by MelanX** [comment]
Duplicate #394

**Comment by MaxNeedsSnacks** [comment]
No longer applicable (also props to Lat for figuring out this mess when updating to 1.16)
