### ISSUE TITLE
Unlimited Quest completions

### ISSUE THREAD

**Issue by yashsavalia1** [FTBTeam/FTB-Quests#422]
If a person on my server leaves their team and makes a new one, they can redo all the quests and gain the loot twice. Is there any way to block someone from accessing the teams menu?

**Comment by TSG-rain** [comment]
Have you solved this problem now? Could you tell me?

**Comment by TSG-rain** [comment]
I know how to solve this problem. The menu can be hidden in the configuration file,But it can't stop players from leaving the team

**Comment by TSG-rain** [comment]
原来支持中文哒
