### ISSUE TITLE
Item list only accepts the first item

### ISSUE THREAD

**Issue by DAmNRelentless** [FTBTeam/FTB-Quests#424]
Hello there!
I am currently experiencing a bug with FTB Quests on Minecraft 1.12.2.

I want a quest that has one of two items as its condition. As soon as one of these are crafted, the quest should be completed.
However if you set this up with an item list, it will only accept the first item in the list.

Here is an example:
I tried making a quest where players have to craft one of two given mana generating plants from Botania.

This is how the quest looks:
![](https://i.imgur.com/o8A47ba.png)
![](https://i.imgur.com/GfTxIQ2.png)

And this is the item list I used:
![](https://i.imgur.com/iuUl9wE.png)

However, the quest is only completed if I craft the Gourmaryllis. If I only craft the Munchdew, the quest is not completed so it seems like it only accepts the first item in the list.
If I change the order of the two plants, the first one is the one that is detected again so it's alway the first item in the list.

I mentioned this on the Discord and another guy has the exact same issue when trying to do that with Sharpening Kits.

Minecraft: v1.12.2
Forge: 14.23.5.2847
FTB Quests: 1.8.1

**Comment by MaxNeedsSnacks** [comment]
Closing because this issue is probably outdated, feel free to reopen if this is still an issue on 1.16+ ^^
