### ISSUE TITLE
How can I find quests for a specific mod (Ancient Warfare 2)

### ISSUE THREAD

**Issue by CookiePowder** [FTBTeam/FTB-Quests#428]
I want to add this mod into the R.A.D modpack, whhich uses FTb Quests, but is it possible for me to get quests for this mod too?

**Comment by MaxNeedsSnacks** [comment]
Quests have to be created by pack developers themselves, so you'd have to make your own or copy them from an existing pack (which I highly recommend ***against*** doing)
