### ISSUE TITLE
Ability to see dependencies of a quest that are in another chapter

### ISSUE THREAD

**Issue by Milesman34** [FTBTeam/FTB-Quests#430]
It would be good if, while editing mode is disabled, you could see the dependencies of a quest that are in different chapters. 

For example, let's say I have 2 chapters, Vanilla and Storage. The Vanilla chapter has a quest for iron ingots. The Storage chapter has a quest for an Iron Chest. The Iron Chest quest requires the completion of the iron ingots quest. However, the player cannot find this out, as there is no indication that the iron ingots quest must be completed to unlock the Iron Chest quest. I suggest that you add this functionality to make it easier to deal with quests in a quest-book with multiple chapters.

**Comment by MaxNeedsSnacks** [comment]
There will probably be "links" in the future, which are basically just empty quests linking to another object in another chapter. You can use these or refer users to the dependency arrows to better explain your quest dependency trees.
