### ISSUE TITLE
Allow us to widen quest windows without making long names

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Quests#434]
![](https://cdn.discordapp.com/attachments/303440391124942858/731416568650530866/unknown.png)

![](https://cdn.discordapp.com/attachments/303440391124942858/731416680563212309/unknown.png)

**Comment by MaxNeedsSnacks** [comment]
For future reference, I'm pretty(?) certain there was a minimum width attribute added to Quests themes that you can use to force a certain quest's panel to be larger
