### ISSUE TITLE
Items Quest deleted related to Thermal expansion mod.

### ISSUE THREAD

**Issue by LnX-OrioN** [FTBTeam/FTB-Quests#437]
I make quests task with thermal expansion's machines in my own modpack but it seems there are deleted after a restart.

this error appears in the last version of FTB quest (1.9.0.6)

EDIT: same error in previous version (1.9)

**Comment by hasrock36** [comment]
Having the same issue, tried to revert to 1.8 but then it doesn't load any quests.

**Comment by LnX-OrioN** [comment]
> Having the same issue, tried to revert to 1.8 but then it doesn't load any quests.

Yes ,i've tried this too. So i put temporarily TE machines in the shop.

**Comment by LnX-OrioN** [comment]
Resolved  since 1.9.0.7 ! thanks
