### ISSUE TITLE
[1.12.2] Repeatable Quests Don't Unlock Other Ones Correctly

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Quests#442]
I'm trying to make a serious of repeatable quests where you submit various mob drops, but I can't set the previous tier as a dependency for the next without it resetting itself.

For example, in the first one you submit 8 Gunpowder, and in the second you submit 16 Gunpowder. I want to make it to where the player can't do the second one until they finish the first one, but both are repeatable (to get money you can use elsewhere in the pack)

Whenever you complete the first one and claim its reward, it locks the second one.

Would you be able to fix this, or have a work-around or something?

**Comment by MaxNeedsSnacks** [comment]
That's an issue with repeated quests that we'll need to solve in future versions, since 1.12 is unsupported unfortunately, sorry about that!
