### ISSUE TITLE
[Suggestion] [1.12.2] Pinned quests should auto-unpin when completed

### ISSUE THREAD

**Issue by vizthex123** [FTBTeam/FTB-Quests#448]
Title. I like the idea of pinning quests you're working on, but they should be removed when finished and/or the reward(s) is (are) claimed

**Comment by WeaselOnaStick** [comment]
that or have a column of completed quests in the menu where you can un-pin them with a hotkey.

**Comment by vizthex123** [comment]
Eh I'd rather have it be fully automated. There's no reason to keep a completed quest pinned.

**Comment by Spongman** [comment]
yes. please do this.

**Comment by Legomonster33** [comment]
> Eh I'd rather have it be fully automated. There's no reason to keep a completed quest pinned.

false

if a quest has a list of instructions how to make a multiblock and what blocks are needed for the multiblock, i would want the quest to remain so i know i have all the correct blocks needed etc

this would be a good feature to be toggleable by the player

**Comment by MaxNeedsSnacks** [comment]
I think this is a thing in newer versions of Quests, so this should no longer be an issue ^^

**Comment by vizthex123** [comment]
But... I wanted it in the 1.12.2 version....
