### ISSUE TITLE
[Suggestion] Allow changing TAB Key Bind Behavior

### ISSUE THREAD

**Issue by mellamokb** [FTBTeam/FTB-Quests#449]
I use the TAB key to open/close inventory.  One of the most annoying things about FTB Quest book, is my muscle memory to use TAB to close the quest interface.  But instead of closing it, it navigates to the next page then I lose track of where I was.  Suggest to be able to change the Key Binding to TAB to close the questbook instead of switching pages.

**Comment by MaxNeedsSnacks** [comment]
We **might** change it to Shift + TAB or a fully configurable key in the future
