### ISSUE TITLE
[1.12.2] FTB Sky Adventures Quest Book Empty

### ISSUE THREAD

**Issue by 80L** [FTBTeam/FTB-Quests#451]
While trying to set up a FTB Sky Adventures on a Server.Pro server the quest book was blank and weve tried downloading the world through single player, reinstalling configs, and other things. Still can't get the quest book to work though. It works fine in single player aswell. We;re using FTB Quests version 1.4.0.109. Screenshot of the quest book below.
![example](https://user-images.githubusercontent.com/68766514/88719302-123e7400-d0f1-11ea-864e-77edbc49c99e.PNG)

**Comment by teqqqie** [comment]
I'm having the same issue with a different server and modpack

**Comment by MaxNeedsSnacks** [comment]
These packs are all using obsolete versions of FTB Quests, there are probably newer pack versions available (for instance on the FTB launcher, in the case of Sky Adventures) that hopefully fix this issue
