### ISSUE TITLE
[1.15.2] tags are not up to date

### ISSUE THREAD

**Issue by TheUntamed** [FTBTeam/FTB-Quests#452]
I wanted to add items to a quest task by tag and had to notice that the tags I can choose from are not the actual tags of the item. To be more specific custom tags that were added by myself e.g. via crafttweaker are not available and tags that I removed the same way are still available.

kubejs has the same problem which makes it more visable:
The black tags with "#" are the tags shown by kubejs, the white tags are the actual tags, 
![Screenshot_1](https://user-images.githubusercontent.com/48363903/88787456-2ab39a80-d194-11ea-8ab4-1f1a9a59af24.jpg)

The tags I can choose in ftbquests:
![Screenshot_4](https://user-images.githubusercontent.com/48363903/88787463-2e472180-d194-11ea-8860-370cb49b177d.jpg)

This also means that a quest can be fulfilled with items that don't actually have the tag anymore.

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in 1.16+ versions of Quests, hopefully
