### ISSUE TITLE
Can't load my worlds

### ISSUE THREAD

**Issue by Naini0712** [FTBTeam/FTB-Quests#456]
Hello.
I have an issue loading worlds.
When I load my world after making quests, Minecraft stopped world's loading.
But it didn't crash.
[23:01:17] [Server thread/INFO] [FTB Quests]: Loading quests from C:\_gdl\instances\Minecraft forge\config\ftbquests\normal
This is latest log in latest.log.

I want to know such an issue has happened before by other players.

If you need mod list and config file, I'll upload.
Minecraft  Version: 1.12.2
Forge Version: 14.23.5.2854
- Mods -
FTBLib-5.4.7.2
FTBQuests-1.9.0.12.jar
and more than 100 mods...

**Comment by MaxNeedsSnacks** [comment]
Do you have any backups for your quests? I'm assuming you added a circular dependency somewhere.
Either way, 1.12 is unsupported, so unfortunately I won't be able to help you with this
