### ISSUE TITLE
Team Reward does not work

### ISSUE THREAD

**Issue by Camooflo** [FTBTeam/FTB-Quests#457]
FTBQuests-1.9.0.12.jar 

Team reward is not working on quests that can be repeated
Everyone is receiving a copy of the reward 

Tested on my server

**Comment by DancingSnow0517** [comment]
same...
![image](https://user-images.githubusercontent.com/60736156/92987032-7eced000-f4f1-11ea-96d4-0cda3c179bdd.png)

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in newer versions of Quests for 1.16+, hopefully, if it is, feel free to reopen!
