### ISSUE TITLE
[1.15] Tags transformed to air

### ISSUE THREAD

**Issue by Maxwelljones** [FTBTeam/FTB-Quests#459]
Hey there. I used tags by manually typing my tag in the questbook (example `{tag:"forge:ingots"}`)
![javaw_8gy9eymruA](https://user-images.githubusercontent.com/3750700/93668247-89f2a480-fa8b-11ea-9fd0-f3f991dc21f6.png)
After pressing accept, it automatically converts to `{id:"minecraft:air",Count:1b}` (that's what I can see when trying to edit it again)
![javaw_j67MCajNou](https://user-images.githubusercontent.com/3750700/93668254-9119b280-fa8b-11ea-9890-9d19327f3c1b.png)
If I don't edit it again, my tag is properly saved and working (when I grab an ingot, it does complete the quest) but it is showing air instead in the quest book which is confusing.
![javaw_wCE4WYYzef](https://user-images.githubusercontent.com/3750700/93668259-937c0c80-fa8b-11ea-8654-b6657c1cb14c.png)
Hope my explanation is enough. Feel free to ping me to get more detailed information.

**Comment by MaxNeedsSnacks** [comment]
To use tags, you'll need to use Item Filters, which is a dependency for FTB Quests: There's a Tag Filter item that works pretty much the way you want it to, just add that as a requirement

**Comment by Maxwelljones** [comment]
Didnt know! Thank you very much for your answer!!
