### ISSUE TITLE
[1.15.2] Empty tooltip when editing mode is false

### ISSUE THREAD

**Issue by Mohatax995** [FTBTeam/FTB-Quests#461]
Minecraft version: 1.15.2
Mod version: 2.0.2.247 and 2.0.2.248
Forge version: 31.2.37
No other mods

Shows empty tooltips when editing mode is false.
![imagen](https://user-images.githubusercontent.com/67057882/94343328-a22c6b80-0017-11eb-8f01-2bdc14618bb2.png)

**Comment by Zayda0221** [comment]
Have the same problem with multiple modpacks using this mod.

namely:
Craft of exile [dissonance]
Life in the village 2

**Comment by Linguardium** [comment]
seems to occur with all tooltips but only when that dialog box is open. Even tooltips for background quest titles are blank.

**Comment by MrPryor** [comment]
Having same problem in Craft to Exile [Dissonance] https://i.imgur.com/uDLmQAO.png

**Comment by casper20051** [comment]
I found a way to fix it, in "FTB-Quests-1.15.2\src\main\java\com\feed_the_beast\ftbquests\gui\quests\PanelViewQuest.java", I moved "theme.drawString(title, x + w / 2F, y + 4, ThemeProperties.QUEST_VIEW_TITLE.get(), Theme.CENTERED);" from line 347 to line 343.
![ftbquests](https://user-images.githubusercontent.com/3000350/96175960-a56d9580-0ef9-11eb-94ce-ab3cd9f48145.jpg)

**Comment by Alexgamer415** [comment]
@casper20051 
This was very helpful, once I actually figured out how to edit the files!

Thanks for the insight.

**Comment by MaxNeedsSnacks** [comment]
Should have been fixed by https://github.com/FTBTeam/FTB-Quests/commit/3e59dd3f7350baf4349f9a3bab0e5269ec93c341
If not, it's definitely fixed in 1.16+
