### ISSUE TITLE
[1.15.2] Cant delete reward tables and streched out gui

### ISSUE THREAD

**Issue by Mohatax995** [FTBTeam/FTB-Quests#462]
Minecraft version: 1.15.2
Mod version: 2.0.2.247 and 2.0.2.248
Forge version: 31.2.37
No other mods

When you edit a reward table and you add an item the gui streches out and you cant see what you are doing.
Also when I delete a reward table it seems to work, but when I exit and enter the world again the reward table appears again, so I cant delete it.

Video: https://youtu.be/6KihS8aZ6Gs
In the video when I make the reward table "new" and I add the planks item to it the gui streches. Then I delete the reward table and leave the world. When Im back the reward table called new is there again.

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in newer versions of Quests for 1.16+
