### ISSUE TITLE
[1.15.2] New quests and changes are not getting saved and its messing up everything I already have

### ISSUE THREAD

**Issue by Mohatax995** [FTBTeam/FTB-Quests#463]
Minecraft version: 1.15.2
Mod version: 2.0.2.247
Forge version: 31.2.37
I have some other mods let me know if you need me to write them here.

For some reason it stops saving the quests and the changes I make. I check the file where they are saved and nothing new is added even if I add new quests.
Also, every time I load the world it messes up the categories on the left. It changes the order randomly, changes the icons, names, etc. Sometimes it even brings back the categories I deleted or it duplicates them.

This started to happen after some days. I dont know if its because I added a lot of quests or if its because I made some reward tables (and they are acting weird, see issue #462 ) or if its random but it started to happen suddenly.

Now I deleted the mod and added it again and its working fine but I still havent added all the quests I had so it may happen again when I add the rest.

**Comment by Maxwelljones** [comment]
Same here. 

**Possible workaround** before fix: I think adding a new quest does save the deletion and keeps the categories in place.

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in newer versions of Quests for 1.16+, hopefully, if it is, feel free to reopen!

**Comment by Maxwelljones** [comment]
Nice one @MaxNeedsSnacks, thank you!
