### ISSUE TITLE
[1.15.2] FTB Quests no repeatable quests option

### ISSUE THREAD

**Issue by VolvoRider** [FTBTeam/FTB-Quests#465]
Hey. At this version I discovered that there no option to make quests repeatable.

**Comment by HockeyZman2000** [comment]
I would really like the option for the repeatable quests on this version as well!

**Comment by MaxNeedsSnacks** [comment]
Repeatable quests are coming back for 1.16 (or 1.17, depending on whether Lat or Mojang is faster)
1.15 won't be getting them as it's unsupported, unfortunately!
