### ISSUE TITLE
Trigger Quest Completion When Applying Tinker's Modifier

### ISSUE THREAD

**Issue by KangyKSLG** [FTBTeam/FTB-Quests#468]
Hi,

I was wondering if it's possible to make a quest that triggers when a Tinker's tool receives a certain modifier. I.E. When you combine a pick with a diamond

**Comment by MaxNeedsSnacks** [comment]
This would have to be added in Tinker's Construct (or an addon) rather than FTB Quests itself as we're trying to move mod integration outside of our own mods, plus 1.12 is an unsupported version, so unfortunately we won't be adding this ourselves anytime soon.
