### ISSUE TITLE
[1.16.3] NPE when using AE2 autocrafting

### ISSUE THREAD

**Issue by Reveter** [FTBTeam/FTB-Quests#469]
Attempting to autocraft with AE2 results in a stacktrace to console and the craft being unable to proceed.

[Stacktrace](https://gist.github.com/Reveter/602fe069bfc25ae81cdda7544a9d5edd)
[log](https://gist.github.com/Reveter/2ae8a02db3e595603ac55a3a01edd007)

appliedenergistics2-8.1.0-alpha.3.jar
ftb-quests-1603.0.2.2.jar

**Comment by ProsperCraft** [comment]
I can confirm that removing FTB-Quests fixed the problems with AE2 autocrafting not working.

**Comment by Seniorendi** [comment]
When i want to start an Autocrafting recipe in AE2 is doesn't work, when i click on the next button nothing happens. When i remove FTPQuests it does work.

Sorry for my english if it's bad, my native language is not english.

**Comment by MaxNeedsSnacks** [comment]
This was fixed 4 days ago in https://jenkins.latmod.com/job/FTB-Quests-1.16.3/3/ according to the release notes

**Comment by Seniorendi** [comment]
I use the latest version(1603.0.2.4).
And in the release notes is only this: 
- Fixed crash with fake players
