### ISSUE TITLE
[1.16.3]Buttons from Reward tables does not really work.

### ISSUE THREAD

**Issue by Seniorendi** [FTBTeam/FTB-Quests#471]
Hey,
When i want to create a Reward table, it does work but the Buttons dies not work. When I type in a name and click accept nothing happens, when it click on cancel also nothing happens. Then i pressed escape, opened the Menu again and there are now 2 Reward tables.
Here a Video(You can watch it in your browser): https://cloud.srendi.de/index.php/s/SAczgCiftSctmca

Sorry for my english if it's bad, it's not my native language.

**Comment by MaxNeedsSnacks** [comment]
See #473
