### ISSUE TITLE
[1.16.3]Reward tables issues

### ISSUE THREAD

**Issue by Seniorendi** [FTBTeam/FTB-Quests#473]
I have a lot of issues with Reward tables.
Issue 1:
#471  

Issue 2:
I have a lot of quests with a lot of Reward Tables for choice Rewards. I do not know when that happens but sometimes shuffles the Choice rewards. Example: I have 2 Quests(A and B) and 2 Reward Tables(C and D), i set a Choice Reward for Quest A with the Reward Table D and a Choice Reward for Quest B with the Reward Table C. Few restarts and new Worlds later shuffles the Choice Reward. So the Reward Table C is at once at Quest A and Reward Table D is at once at Quest B. I Can make a video when i figure out how to reproduce.

Issue 3:
When i rename a Reward Table it does not work and the Reward Table is broken for the Choice Reward. Vid(You can watch it in your Browser) -> https://cloud.srendi.de/index.php/s/3dqkMZocPJ7N3cA

Sorry if my English is bad, it's not my Native Language.

**Comment by Seniorendi** [comment]
For Issue 3:
There is no Exception in the console/log. Just a save Message when i pause my game.
![image](https://user-images.githubusercontent.com/67484093/97109398-4ebf4300-16d3-11eb-84b8-54434c995d82.png)

**Comment by Seniorendi** [comment]
It's impossible to play with issue 2 because i get the wrong rewards for the quests...

**Comment by MaxNeedsSnacks** [comment]
Should all be fixed in 1.16.5 (1605) releases, hopefully!
