### ISSUE TITLE
[1.16.3]Crash with java 14

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Quests#474]
Hello,
When using FTBQuests 1603.1.0.6 in a modpack (forge 31) and with java 14, it crashes. 
Here's the crash-log : https://gist.github.com/jinkhya/108598b4fe72724c92983b3b852df863
Thanks in advance.

**Comment by Gbergz** [comment]
Happens in Java **8** aswell. **(Forge 34.1.32)**

**Comment by Xplodin** [comment]
Happens with forge 34.1.34 too any java

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in newer releases
