### ISSUE TITLE
[1.16.3] Unable to join servers

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Quests#476]
FTBQuest prevents players from joining servers, until they've tried once and the server is restarted.

server latest log: https://gist.github.com/NillerMedDild/337b37d005e69d0d8d5a30780f81b4a5
client latest log: https://gist.github.com/NillerMedDild/435de29e9e60906275e7ac0aea157f5f

**Comment by MaxNeedsSnacks** [comment]
Fixed in newer releases
