### ISSUE TITLE
FTB-quests-1603.1.0.8 Crash on Startup

### ISSUE THREAD

**Issue by Grant-K** [FTBTeam/FTB-Quests#478]
on minecraft startup game crashes with the following error: java.lang.NullPointerException: Property extra_quest_shapes doesn't have a default value!
Full Crash Log can be found here:https://pastebin.com/DKHAgRSM

**Comment by NillerMedDild** [comment]
I think it's likely that this issue is caused by Forge version above `1.16.3-34.1.25`

**Comment by Grant-K** [comment]
I backdated forge to 34.1.24 and that worked for me so for now ill leave it on that version until a mod update requires a forge update.

**Comment by NillerMedDild** [comment]
I don't think you should close this issue, it hasn't been resolved :)

**Comment by Grant-K** [comment]
Can confirm at time of writing this FTB Quests mod will crash the client if used with a version of forge above 1.16.3-34.1.25 up to Forge-34.1. 35 which is latest at time of writing this.

**Comment by 3x1at1on** [comment]
Same issue even with Forge 34.1.39

**Comment by MaxNeedsSnacks** [comment]
Should be resolved for newer releases
