### ISSUE TITLE
[1.16.3] FTB Quest Task Progress resetting on every world load.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Quests#479]
Player reported this to my issue tracker: https://github.com/The-Nexus-Project/Limitless-3/issues/24 (**More info there.**)

**Forge:** 34.1.25
**FTB Quests:** ftb-quests-1603.1.0.11

Questing progress task seems to get reset every time a player rejoins a world. (**in sp & mp**).
Also completed quests seem to show their "Quest Completed" toasts every time you re-enter a world.

Quest progress is saved when you have the quest items in your inventory, but as soon as you put them away and relog, the quests get reset to 0.
It's like the the quest forgets that you completed the quest.

Strange issue.

**-** Gbergz

**Comment by GarthF** [comment]
Rolled back to ftb-quests-1603.1.0.5 and the problem goes away, so somewhere between there and .11 it went wonky.

**Comment by Gbergz** [comment]
> Rolled back to ftb-quests-1603.1.0.5 and the problem goes away, so somewhere between there and .11 it went wonky.

Was just about to comment this, downgraded to 1.0.5 and the problem is gone.

**Comment by benbenlaw** [comment]
Yeah it broke the whole of my modpack for players as well
