### ISSUE TITLE
[1.16.3]assigning reward tables to multiple quest's 

### ISSUE THREAD

**Issue by MasterSloth1** [FTBTeam/FTB-Quests#480]
FTB-quests = 1603.1.0.11
FORGE = 34.1.42
when you try assigning a reward to multiple quests at once it does nothing, but assigning them individually works perfectly
**reproduction steps**
select multiple quests with control+A
right click quest -> add reward to all
select reward type and watch as it goes back to the quests page
go into a quest to see nothing assigned to the rewards for the selected quests

**Comment by MaxNeedsSnacks** [comment]
Might be resolved in newer versions, can you check again using the 1605.2 versions?

**Comment by matthyno** [comment]
Tried this on 1605.2.1-build.39, Forge 36.1.0. Same issue.
