### ISSUE TITLE
Crash when trying to go into the Quests GUI

### ISSUE THREAD

**Issue by Rasblue** [FTBTeam/FTB-Quests#484]
Last night i made about 100 quests, today i opened Minecraft and when i was about to continue making more Quests it crashed just by clicking the Quests GUI in my inventory, need help.
[crash-2020-11-11_16.12.41-client.txt](https://github.com/FTBTeam/FTB-Quests/files/5527495/crash-2020-11-11_16.12.41-client.txt)

**Comment by seilexfr** [comment]
Same here but i was already in game

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue in 1.16+ versions of Quests anymore, hopefully, if it is, feel free to reopen!
