### ISSUE TITLE
[1.16.4] How can i transfer Fluids or Forge Energy for completion tasks?

### ISSUE THREAD

**Issue by cyberpunkbln** [FTBTeam/FTB-Quests#485]
Hello,

in the 1.16.4 Version i have only the Quest-Book and i was happy that i can use Forge Energy for Quests or Fluids.

But when i give the Quest 10000 FE or 1000ml Water i don't know how i can deliver this to complete the Quest?

thx

**Comment by NillerMedDild** [comment]
At the moment, you can't, the blocks have not been re-added yet.

**Comment by cyberpunkbln** [comment]
That is a pity, i'm hopefully that the blocks will ne added in the near future. Energy and Liquid Transfer is the greatest Thing, in my opinion.

For now how i can use an energy cell / tabks from various mods with nbt-data where the nbt-data says energy-cell full with x FE or with x ml Liquid?

I understand that i can choose an full bucket from minecraft, nut tanks and cells with nbt-data?

**Comment by NillerMedDild** [comment]
I think you can choose tanks with NBT data :) not sure though, to be honest.

**Comment by cyberpunkbln** [comment]
Ah yes i must choose from inevntory with an full energy cell:) and then can i see the nbt-data.

For now i study the changelogs on curseforge and hope for the new blocks;).
