### ISSUE TITLE
quest progress not syning between team members

### ISSUE THREAD

**Issue by Spongman** [FTBTeam/FTB-Quests#486]
I'm running ftb-quests-1502.0.2.252.jar (in 'Craft to Exile [Dissonance]') on a server, i have 2 playesr that are in a team together, but FTB quest progress isn't shared between the players.

**Comment by Spongman** [comment]
this works in 1.12 (ME^5), but not in 1.15 apparently ?

**Comment by Spongman** [comment]
I tried adding the 1.15 ftp-teams mod to both server & clients, and used `/ftbteams` to add both players to an ftb team, but that didn't help. still not synced.

**Comment by MokahTGS** [comment]
This has been reported for 1.16+ as well.  Seems to be a 1.15 and forward issue.

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #470
