### ISSUE TITLE
[Feature-Request] Deactivate Mods or Items?

### ISSUE THREAD

**Issue by cyberpunkbln** [FTBTeam/FTB-Quests#487]
Hello,

it will be great if i can deactivate and activate Mods or Mod-Items.

At the moment i deactivate core recipies with an datapack and give the core items per quest reward, but a full deactivating from an mod will be great.

Give it workarounds?

**Comment by MaxNeedsSnacks** [comment]
This won't be part of the FTB Quests feature set; your way of removing recipes and awarding these items as Quest rewards is fine as is if you want these items to be "special", and as for completely removing mod items, that's completely outside of quests' scope
