### ISSUE TITLE
Some overlays displays weird

### ISSUE THREAD

**Issue by goku727** [FTBTeam/FTB-Quests#495]
**Info overlays**
If you have a quest with a food reward, when you hover the food item, the AppleSkin overlay woth food value displays weird
![image](https://user-images.githubusercontent.com/34101063/100539339-0ba64180-3236-11eb-8bc3-4b8aa9e62513.png)
This appends with AppleSkin Overlay, and the Quark tooltips (amor points with icons, etc) [only found this for now]

But, if you are in editing mode, all shows fine (only the minecraft info about the item displays under quest)
![image](https://user-images.githubusercontent.com/34101063/100539377-427c5780-3236-11eb-82f9-2c182d52f718.png)

**Quest complete toast misses background**
When the toast appear, and you hover the above any quest, the toast will misses the background and only shows text and icon
![image](https://user-images.githubusercontent.com/34101063/100539479-1f05dc80-3237-11eb-9f8e-6c309e4bf792.png)

Like before, this not happend in editing mode
![image](https://user-images.githubusercontent.com/34101063/100539499-4492e600-3237-11eb-9d53-7e1c420cf869.png)

**_Mods/Forge Version_**
Forge: 1.16.4-35.1.6

FTBQuest: 1604.1.1.15
FTBGuiLib: 1603.1.1.25 
AppleSkin: mc1.16.2-forge-1.0.14
Quark: r2.4-276
AutoRegLib: 1.6-46

**Comment by MaxNeedsSnacks** [comment]
Should(?) be fixed by the 1605.2 releases
