### ISSUE TITLE
Classpath or namespace error on 1.12 branch causes a crash to desktop

### ISSUE THREAD

**Issue by tyggna** [FTBTeam/FTB-Quests#498]
I tried to get a build environment to just fix this myself because it looks easy, but I couldn't get it running.  Since I assume you still have a build environment working for the 1.12 branch, could you check this classpath problem?  I've verified that the class file is in the .jar, but for some reason it just doesn't see it on load.
I'm using FTBLib-5.4.7.2 which quests says it requires.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Quests (ftbquests)
[B#607]  Caused by: java.lang.NoClassDefFoundError: com/feed_the_beast/ftbquests/integration/botania/TileTaskScreenCoreBotania
[B#607]  	at com.feed_the_beast.ftbquests.integration.botania.BotaniaIntegration.preInit(BotaniaIntegration.java:22)
[B#607]  	at com.feed_the_beast.ftbquests.FTBQuests.onPreInit(FTBQuests.java:76)
[B#607]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#607]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

**Comment by MaxNeedsSnacks** [comment]
This is a weird one. The file physically exists, so I honestly have no idea where your issue is coming from... I'll ask Lat whether he still has a 1.12 workspace
