### ISSUE TITLE
[1.16.4] Command Rewards auto-claim when auto-claim is disabled

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Quests#499]
Command Rewards auto-claim when auto-claim is disabled

- ftb-quests-1604.1.1.15

Quest: 
![billede](https://user-images.githubusercontent.com/21295394/100663371-777fcb80-3356-11eb-9ea4-e65c6c12468c.png)

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue on newer releases?

**Comment by NillerMedDild** [comment]
Not sure, will check :)

**Comment by NillerMedDild** [comment]
Nope all good now :D
