### ISSUE TITLE
[1.16.4] Data statistic duplication

### ISSUE THREAD

**Issue by Winddbourne** [FTBTeam/FTB-Quests#502]
I'm seeing a weird issue on the statistics page when I use data in a quest . . . the data line I reference suddenly gets a second or even a third entry. 

Sometimes one of the entries will be decimal and the rest look like integers. I haven't done much poking around with it yet beyond confirming that it happens, and I don't know whether it will impact the quests either but I figured you would want to know about the issue just in case. 

I'm using ftb-quest-1604.1.1.15 and I did test that the problem goes away if I remove the quest, and changes where it impacts if I change the data a quest is looking at. I also  made a new pack with just FTB Quests installed and tested it to make sure it wasn't caused by a mod conflict of some type. 

Here are some screen shots. I've included one with damage taken that shows the integer decimal mismatch, and two using mobs killed where both are using integers and I've updated my kill count to show it is tracking. I didn't try to update with the mismatch since I'm not looking to cause problems, just to report the bug so it can be investigated.  

Hope this helps! 

![2020-12-03_21 01 30](https://user-images.githubusercontent.com/24589533/101260069-1ca1f780-36fb-11eb-8006-173c46645480.png)

![2020-12-05_13 03 34](https://user-images.githubusercontent.com/24589533/101260075-20357e80-36fb-11eb-985e-fc9b7ae54754.png)

![2020-12-05_13 08 05](https://user-images.githubusercontent.com/24589533/101260076-23c90580-36fb-11eb-9d3b-95c6d56de1f5.png)

**Comment by MaxNeedsSnacks** [comment]
This is a **very** weird issue that I haven't really been able to reproduce unfortunately, so I'll just close this for now
If this still pops up though, do feel free to reopen it, especially if you have anymore details on how to make this happen ^^
