### ISSUE TITLE
blank questbook when transferring to server

### ISSUE THREAD

**Issue by teqqqie** [FTBTeam/FTB-Quests#503]
I'm playing the stoneblock 2 modpack on curseforge. I migrated my singleplayer world to a server, but the questbook is blank on the server. How do I get the quests and my progress on them to show up? Everything else about my world transferred properly.

**Comment by Xplodin** [comment]
having the same issue

**Comment by MaxNeedsSnacks** [comment]
We don’t support 1.12 anymore, unfortunately. You can try using a later version of Quests for 1.12 to see if that fixes it, but other than that there’s not much we can do since that pack has been discontinued, as well
