### ISSUE TITLE
Lack of Reward Collector documentation

### ISSUE THREAD

**Issue by Snerky** [FTBTeam/FTB-Quests#504]
I'm trying to automate a repeatable quest. I'm piping the required item into a task screen, and the rewards are appearing in my inventory. I'd rather they went into a block, as the current setup causes the rewards to fill my inventory and make playing a nightmare, and I thought that the Reward Collector sounded like the perfect solution! Unfortunately, nobody on the internet seems to know how it works.

I've placed it down, configured it with the quest that I've automated, and nothing happens. Neither placing it next to a chest nor connecting a pipe to it yielded any results. Placing it down adjacent to the Task Screen likewise did nothing. The rewards still go to my inventory.

I'm playing MC Eternal, Minecraft 1.12.2, FTB Quests 1.9.0.10. Any insight at all would be fantastic.

**Comment by fatboychummy** [comment]
Bumping this as I, too, am confused about this particular thing.

I've placed down the reward collector, have pipes pulling items from it and have chests sitting directly on it. Neither fill with the reward items, but my inventory gets filled.

**Comment by Dan-Halen** [comment]
further bumping this but adding that i have seen coins coming out of the collector but i notice that the id's dont match with the task screen id's, so i think it caught some coins from an actual quest. ive started going thru them to see if i can find any matches because those should still be able to collect for you

**Comment by MaxNeedsSnacks** [comment]
Neither the quest chest nor the reward collector should be used honestly, both of them are buggy messes and have been removed in 1.16 (whether they'll be readded is up for debate still)

As for the lack of documentation, that probably won't be worked on until these things are added back (if at all)
