### ISSUE TITLE
[1.15.2]Quest icons blocking titles

### ISSUE THREAD

**Issue by MagentaSS** [FTBTeam/FTB-Quests#505]
game version 1.15.2
mod version:ftb gui lib 1.0.0.14,ftb quests1502.0.2.252
Problem:
Quests not yet completed will block the titles of another quest when your mouse is hovering on them.Besides,The "√" of a completed quest also blocks the title.
![BUG1](https://user-images.githubusercontent.com/33283267/102092545-2514d380-3e5b-11eb-911b-b7820bca35b7.png)
![BUG2](https://user-images.githubusercontent.com/33283267/102092564-29d98780-3e5b-11eb-9c99-a94ed94df818.png)

**Comment by MagentaSS** [comment]
I don't know whether it is caused by the library or the mod itself.This is a great problem for modpack players,and I have worked on them for a few days.I don't want to use other quest mods because it may cost me a lot of time remaking all the quests and they are not as convenient as FTB quests.

**Comment by minecraftindad** [comment]
Mod author suggested we simply move to 1.16.   I have the same issue as you, and happened to ask on Discord.  Unfortunately, I was told they are no longer offering bug fixes for 1.15.

**Comment by MagentaSS** [comment]
> Mod author suggested we simply move to 1.16. I have the same issue as you, and happened to ask on Discord. Unfortunately, I was told they are no longer offering bug fixes for 1.15.

I think that's a good idea,though it may take some time for some mods to move to 1.16.I hope the quests saved can successfully port to 1.16.Sometimes I think whether the mod team is still supporting 1.15 because there is only alpha versions and I now know that it is no longer supported.Thanks!

**Comment by alfuken** [comment]
And I just walked in with the same issue... Too bad they don't support 1.15, it's still a very popular version, almost as much as 1.12
D-move, if you ask me...

**Comment by alfuken** [comment]
And I just walked in with the same issue... Too bad they don't support 1.15, it's still a very popular version, almost as much as 1.12
D-move, if you ask me... @FTBTeam

**Comment by MaxNeedsSnacks** [comment]
With every major version release, the mod's codebase changes more or less drastically; just recently, we switched to a multiplatform framework that allows us to develop for Fabric and Forge at the same time -- and because of this, it's **exceedingly** difficult to support other versions than the latest ones available, especially since Forge officially dropped support for 1.15 as well.

This rendering glitch has been fixed on 1.16 though, as Lat has stated on Discord

**Comment by alfuken** [comment]
@MaxNeedsSnacks is there a specific commit for that fix? is it really that hard to backport this one bugfix?

**Comment by MaxNeedsSnacks** [comment]
It might be specifically https://github.com/FTBTeam/FTB-Quests/commit/193fb6b4d2276575c1dbb7e536da7db73688c3fe, but as you can see that's a call to FTB GUI Library, which has also been updated and received multiple fixes since then

**Comment by alfuken** [comment]
I see... that's beyond my current java level :( Pity. Thanks though.
