### ISSUE TITLE
FTB-Interactions/quest: an eggsalent endevour

### ISSUE THREAD

**Issue by RainbowSkunk** [FTBTeam/FTB-Quests#506]
I shift clicked all my eggs to submit them and when the quest was complete it instantly gave me all the rewards except the hypogrigh egg. Now my quest shows complete and the rewards claimed however i don't have the egg.

**Comment by MaxNeedsSnacks** [comment]
This seems to be an issue with the Interactions quests rather than the mod, and 1.12 is unsupported unfortunately
