### ISSUE TITLE
Randomly switching quest order/positions in GUI

### ISSUE THREAD

**Issue by Shorepion** [FTBTeam/FTB-Quests#507]
![order](https://user-images.githubusercontent.com/24994890/102801486-94d41280-43b5-11eb-8f80-0e910ec44410.JPG)

The order of the Quest in the GUI are not fixed. 
After editing quests in different chapters it changes the quest order randomly? actual first? - Im not sure.
Is there a method to fix individual quests to a certain postition Im not aware of?

MC 1.16.4
ftb-quests-1604.1.1.18

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in 1605.2 releases of FTB Quests
