### ISSUE TITLE
[1.16.4] Crash with Optifine

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Quests#508]
When clicking an item in FTBQ to see it's recipes, the game crashes. Only happen when Optifine is installed.

### Versions
- ftb-quests-1604.1.1.19
- ftb-gui-library-1604.1.1.26

### Logs
https://pastebin.com/epMXGe9H

**Comment by fachao** [comment]
I have the same issue; not sure what optifine is doing, but they seem to not play nice with many new/updated mods

**Comment by MaxNeedsSnacks** [comment]
Might(?) be fixed by FTB Quests 1605.2 releases; either way, Optifine is unsupported, but if this still pops up, I might try and find a quick fix for it
