### ISSUE TITLE
Minecraft crashes when playing LifeInTheVillage2 mod using CurseForge

### ISSUE THREAD

**Issue by alan-czajkowski** [FTBTeam/FTB-Quests#512]
**Modpack Version**:
* see crash file link

**Issue**:
* trying to play Life in the village 2 mod using CurseForge, Minecraft crashes during regular play, nothing special is happening when it crashes (just while normal building or destroying gameplay)

**Link to Log or Crash File Paste**:
* https://paste.feed-the-beast.com/view/8ea40b32

**Is it Repeatable?**:
* game always crashes after a few mins of play

**Mod/s Affected**:
* Life in the village 2 - v1.10a (using CurseForge v0.0.20)

**Known Fix**:
* none

**Comment by MaxNeedsSnacks** [comment]
This seems to be a modpack issue rather than a mod issue; please report it to the pack's issue tracker instead

**Comment by alan-czajkowski** [comment]
where would this modpack issue tracker be?

**Comment by MaxNeedsSnacks** [comment]
They don't have one linked on their CurseForge page, oh dear...

You could try asking in their discord though, that one ***is*** linked on their CurseForge page:
https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2
