### ISSUE TITLE
[1.12.2] Task Screen not displaying progress until completion. 

### ISSUE THREAD

**Issue by Vulant** [FTBTeam/FTB-Quests#513]
Version: FTB 9.0.15, MC 1.12.2

Issue:
When pairing a task to the task screen, for example collect 100 oak wood, the screen is supposed to display the item count progress. 

What happens instead is the count is not shown until the quest is completed, then it will display 100/100. So if I put in only 50 wood, I’d expect the task screen to show 50/100 just like what’s shown in this mod’s task screen wiki page and demonstration video. 

I could technically just use the progress screen to give some sort of indication of how many objects are left, but it is sorted by category and not individual tasks so it is only half reliable.

**Comment by MaxNeedsSnacks** [comment]
Screens are currently disabled and will be reworked for 1.16+ versions of FTB Quests. As for 1.12, we unfortunately can't support that version for anything other than major bug fixes anymore, sorry about that!
