### ISSUE TITLE
World crashes when going to quest screen while on a team

### ISSUE THREAD

**Issue by TheQKnight** [FTBTeam/FTB-Quests#515]
Version: 1.12.2
FTB Quests: FTBQuests-1202.9.0.15.jar

[crash-2021-01-20_13.57.01-client.txt](https://github.com/FTBTeam/FTB-Quests/files/5845532/crash-2021-01-20_13.57.01-client.txt)

**Comment by MaxNeedsSnacks** [comment]
I can't seem to reliably reproduce this issue, so it's probably an issue with the way your quests are set up rather than with the mod, but we've also stopped supporting 1.12 versions of FTB Quests. See if this issue persists with a different set of quests
