### ISSUE TITLE
[1.12.2] Loot Crate Opener loses items when fed too quickly

### ISSUE THREAD

**Issue by MirrorImageQS** [FTBTeam/FTB-Quests#516]
Version 9.0.15, MC 1.12.2
Encountered on CurseForge modpack Antimatter Chemistry v1.2.33

I did some testing with a Loot Crate Opener and determined that I was getting significantly fewer rewards than I should be as compared to opening manually. I tested several variations on how to insert and extract items from an opener, and I believe the issue is some form of the following:

When multiple crates are inserted in a single stack, the quantity of rewards is only tracked for one hit of each roll or item until that item is removed. If more than 1 loot crate would roll the same rewards, only the first roll's worth is kept. The following table contains my data on that:

|                   |          |        |                    | Servos (1) |         | Servos (4) |          | Servos (64) |          | Hopper/Servo |          | Hopper/Hopper |       | Hopper/Speedy Hopper III |          | Hopper / Transfer Node |      | Servos (artif. Slow) |      |
|-------------------|----------|--------|--------------------|------------|---------|------------|----------|-------------|----------|--------------|----------|---------------|-------|--------------------------|----------|------------------------|------|----------------------|------|
| Reward            | Quantity | Weight | Expected      Hits | Quantity   | Hits    | Quantity   | Hits     | Quantity    | Hits     | Quantity     | Hits     | Quantity      | Hits  | Quantity                 | Hits     | Quantity               | Hits | Quantity             | Hits |
| White Antimatter  | 8        | 1      | 8.53           | 40         | 5       | 24         | 3        | 0           | 0        | 40           | 5        | 64            | 8     | 104                      | 13       | 72                     | 9    | 120                  | 15   |
| Magnesium Sulfate | 1        | 1      | 8.53           | 5          | 5       | 0          | 0        | 1           | 1        | 6            | 6        | 5             | 5     | 7                        | 7        | 7                      | 7    | 7                    | 7    |
| Caffeine          | 1        | 1      | 8.53           | 7          | 7       | 1          | 1        | 1           | 1        | 10           | 10       | 8             | 8     | 4                        | 4        | 13                     | 13   | 10                   | 10   |
| Rubidium          | 1        | 5      | 42.67           | 37         | 37      | 16         | 16       | 1           | 1        | 26           | 26       | 25            | 25    | 30                       | 30       | 42                     | 42   | 39                   | 39   |
| Hassium           | 1        | 1      | 8.53           | 3          | 3       | 3          | 3        | 0           | 0        | 8            | 8        | 6             | 6     | 6                        | 6        | 5                      | 5    | 13                   | 13   |
| Potassium         | 2        | 1      | 8.53           | 20         | 10      | 8          | 4        | 0           | 0        | 16           | 8        | 10            | 5     | 10                       | 5        | 24                     | 12   | 14                   | 7    |
| Zinc              | 2        | 1      | 8.53           | 22         | 11      | 2          | 1        | 2           | 1        | 14           | 7        | 8             | 4     | 8                        | 4        | 18                     | 9    | 14                   | 7    |
| Nitrogen          | 2        | 1      | 8.53           | 24         | 12      | 4          | 2        | 4           | 2        | 16           | 8        | 10            | 5     | 22                       | 11       | 20                     | 10   | 14                   | 7    |
| Oxygen            | 4        | 1      | 8.53           | 24         | 6       | 8          | 2        | 0           | 0        | 20           | 5        | 24            | 6     | 24                       | 6        | 24                     | 6    | 44                   | 11   |
| Sulfur            | 4        | 1      | 8.53           | 28         | 7       | 4          | 1        | 0           | 0        | 28           | 7        | 16            | 4     | 20                       | 5        | 20                     | 5    | 24                   | 6    |
| Carbon            | 4        | 1      | 8.53           | 20         | 5       | 4          | 1        | 0           | 0        | 44           | 11       | 16            | 4     | 28                       | 7        | 40                     | 10   | 24                   | 6    |
| Total Hits:       |          |        | 128                |            | 108     |            | 34       |             | 6        |              | 101      |               | 80    |                          | 98       |                        | 128  |                      | 128  |
| % Expected Hits:      |          |        |                    |            | 0.84375 |            | 0.265625 |             | 0.046875 |              | 0.789063 |               | 0.625 |                          | 0.765625 |                        | 1    |                      | 1    |

Notes on that table:

- Each loot crate provided two rolls worth of rewards, for a total of 128 expected rolls per stack.
- Quantity refers to the actual number of outputs that item provided in a test. Hits is the calculation of how many times that reward would have been triggered based on the quantity that roll returns. Hits is the more important result per test; Quantity is just the way to calculate it.
- Servos 1/4/64 refers to the items/operation on a Thermal Dynamics Resonant Servo inserting into the Opener. Exporting from the Opener was done with a Resonant Servo at 64 items/operation.
- Hopper/Servo used a Hopper to insert and a Resonant Servo to extract
- Hopper/Hopper used Hoppers to both insert and extract
- Hopper/Speedy Hopper III used the Speedy Hoppers mod to extract
- Hopper/Transfer Node used an Extra Utilities 2 Transfer Node with a full stack of Upgrade Speed (Ultimate) modifiers, meaning it's extracting at the fastest rate it can.
- Servos (artif. slow) is a repeat of the Servos 1 test, except that instead of letting the servo run at normal speed, I instead ran it slower with a Redstone Timer with a long enough delay that the servo removing from the Opener had enough time to remove all items.

Not sure if my theory is entirely correct, but whatever the case, those numbers definitely seem to correlate that the faster items are inserted into the opener and the slower that they are exported, the more rewards that are lost in the process.

**Comment by MaxNeedsSnacks** [comment]
The Loot Crate Opener, like most automation tools in FTB Quests, is currently a bit of a mess and will be reworked for 1.16+ releases. As for the 1.12 version, we unfortunately don't support it anymore except for major bugfixes
