### ISSUE TITLE
Click on item bypasses recipe

### ISSUE THREAD

**Issue by ClaudiusMinimus** [FTBTeam/FTB-Quests#517]
I had a player report the following for ftb-quests-1604.1.1.21. Can confirm this happens in both my 1.16.5 packs
> There's an issue with checking recipes from quests: when you click on required item in quest to see it's recipe, then mouse button down shows it's recipe. But if there happens to be a component under your cursor, then on mouse button up JEI switches to the component recipe instead. so if you just quickly click on quest item, there's high chance you'll see recipe of one of it's components instead of item itself.

Minecraft 1.16.5
Forge: 36.0.1
FTB Quests: 1604.1.1.21

**Comment by MaxNeedsSnacks** [comment]
Does this still happen in 1605.2 versions?

**Comment by Naxanria** [comment]
This sounds more like a Minecraft thing, the mouse button down is being send to the new screen, and if it overlaps with an item in jei's view it will see it as being clicked, and go to the recipe of clicked on.

**Comment by Rodg88** [comment]
> 
> 
> Does this still happen in 1605.2 versions?

I'm getting it in 1605.2.1 build 39

Maybe a fix could just be go to JEI for the recipe on mouse up, instead of mouse down?

**Comment by GregariousJB** [comment]
Still happening in 1605.2.1, but is this in reality a JEI issue? I don't know. 

Also found this on the JEI issue tracker; https://github.com/mezz/JustEnoughItems/issues/2327

**Comment by GregariousJB** [comment]
Just to let others know what I just found out - it seems this issue might be fixed in this JEI commit: https://github.com/mezz/JustEnoughItems/commit/5097e3df0cc15dbc9d45195cf2bf3fde44c2a0ee

**Comment by MaxNeedsSnacks** [comment]
Doesn't seem to be as people have still reported this happening after this commit :/
I'll look into what's causing this soon(tm)
