### ISSUE TITLE
[MC 1.16] Two players in a party but quests are not shared?

### ISSUE THREAD

**Issue by ginokok1996** [FTBTeam/FTB-Quests#518]
We are in a party of 2 people.
When the other completes quests it isn't completed for the other person.

I remember when using this mod in 1.12 this used to work.
Is this a known bug?
Or is there a way to fix this?

**Comment by Sioniraj** [comment]
I hope it's already known by Dev's.

if not -> @LatvianModder this one "issue" needs to be fixed asap, if possible. **Thank you.**
Duplicate of #470 #486

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #470
