### ISSUE TITLE
Quests Not Completing 

### ISSUE THREAD

**Issue by EchoSierra3713** [FTBTeam/FTB-Quests#519]
I Have been doing the quest chains for the blue prints and only certain quests are completing. I have created the Saloon blueprint twice now and it won't complete (Yes I completed the Villager houses quest first). I have also made two Aqua Bases and the quest won't complete. The Moderate house Next to it is complete though. The Watch Tower, Green House, and Mineshaft Entrance did not complete either. 
![image](https://user-images.githubusercontent.com/77905965/105618818-aeec8080-5db9-11eb-9135-5afd30051cca.png)

**Comment by MaxNeedsSnacks** [comment]
This is most likely an issue with how the quests in this pack are configured, rather than an issue with FTB Quests itself. Please check back with your modpack's author to fix this
