### ISSUE TITLE
Quest Database Not Found 

### ISSUE THREAD

**Issue by Cosmortal** [FTBTeam/FTB-Quests#520]
My last resort was to post here. I have tried uninstalling mods, activating admin edit mode, importing the quest database. Nothing works.

My main issue is that no quests pop up in the GUI at ALL. When I try to refresh. It says "Quest Database Not Found".

At first I thought it was FTB but uninstalled and that didn't work so I uninstalled BQ and still nothing pops up for either quest menus.

I just don't know what to do any more. I wanted to create my own Modpack cause the popular ones have WAY too many mods i don't want or need. I even tried to copy Roguelike Dungeons and Adventures mod questing setup exactly. But still same problem. What the heck.

**Comment by MaxNeedsSnacks** [comment]
This doesn't seem to be something we can fix, unfortunately
