### ISSUE TITLE
I clicked an info button while creating my own quests and desktop crashed on a server

### ISSUE THREAD

**Issue by koalalord9999** [FTBTeam/FTB-Quests#522]
https://pastebin.com/JwnKjAXs -- still not sure what I clicked to cause this one
https://pastebin.com/1v3JZpGd -- Clicked one of the info things that pops up after CTRL Clicking a quest in edit mode

**Comment by MaxNeedsSnacks** [comment]
This should be fixed in 1605.2 releases
