### ISSUE TITLE
Quest "Loot rewards" are switching places, but keeping the correct icon

### ISSUE THREAD

**Issue by koalalord9999** [FTBTeam/FTB-Quests#524]
I don't know what's going on - but I have 4 tiers of loot rewards currently and they are supposed to be tied with progression (aka getting a higher tier one before you hit the correct progression mark will actually really mess up progression). Every time I close and restart teh game, the loot rewards seem to switch places with other tiers.

My basic quest lines are supposed to give food, but they give tier 3 resources. the things that are supposed to give t3 resources are giving t1 resources, and t2 is giving food, while t1 stuff is giving t2. I really have no idea wtf is going on, but it's kinda annoying lol especially since I just posted this to my modpack, and as soon as you load it up, it's already messed up :S

**Comment by MaxNeedsSnacks** [comment]
Fixed in FTB Quests 1605.2
