### ISSUE TITLE
Game crashes when converting to tag

### ISSUE THREAD

**Issue by warmluft** [FTBTeam/FTB-Quests#526]
Converting a requirement for quest completion from block to tag (in this case, oak log) crashes my game, here is the crash log.
Version is 1.16.4, Forge version is 35.1.37 and mod version is 1604.1.1.21

https://pastebin.com/yhFagQRU

**Comment by benserwa** [comment]
Came to report the exact same bug.

**Comment by MaxNeedsSnacks** [comment]
Fixed in FTB Quests 1605.2
