### ISSUE TITLE
crashing when clicking the quest book after deleting some mods

### ISSUE THREAD

**Issue by Li-ng** [FTBTeam/FTB-Quests#529]
heres the log
https://paste.ubuntu.com/p/9FPYd6RnVw/
the mods are not specific , it happens either deleting two mods

**Comment by MaxNeedsSnacks** [comment]
This is quite an odd issue... 1.12 is unsupported anyways, but what mods specifically did you delete in your case?

**Comment by Li-ng** [comment]
After pasting this issue i tried many more times, and any mod i deleted will crash, only one thing in common is that they are all the mods i used to use during editing the quests,
(the two specific mods i used to tell you are adpother  https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms,
and Journey into the light https://www.curseforge.com/minecraft/mc-mods/journey-into-the-light-mod)
and now i cant delete any mod i don't want to use anymore, and i have made almost 200 quests and i don't want to start from the beginning. so I'm really really looking forward the fix. 
thanks you a lot
