### ISSUE TITLE
[1.16.5] Crash on Startup

### ISSUE THREAD

**Issue by Xaikii** [FTBTeam/FTB-Quests#532]
With the latest version of FTB Quests it crashes on startup.

Crashlog: https://pastebin.com/kcywt2MS

Versions:
---
Minecraft: 1.16.5
Forge: 36.0.13
Architectury: 1.5.108-forge
FTBQuests: ftb-quests-1605.2.0-build26-forge

**Comment by MaxNeedsSnacks** [comment]
what version of ftb gui library are you using?

**Comment by Xaikii** [comment]
it was on "1603.1.1.25-forge". I looked and I forgot to update it for a while now. After updating the crash is resolved.
