### ISSUE TITLE
Quests not working in multiplayer

### ISSUE THREAD

**Issue by Diversion98** [FTBTeam/FTB-Quests#535]
Hi,

I'm making a modpack and I'm running a server with it.

The problem is if the player plays in single player, quests work correctly.
It detects items in inventory and gives rewards properly.

If we play on the server nothing works correctly.

1. Items won't get detected so you can't complete quests that requests items.
2. The player can't check a check mark so you can't complete quests with a checkmark.
3. If we change the editing mode of a player, the player wont get the editing mode.
4. The quest I completed in singleplayer is already completed on the server, even if I make a new server with no playerdata. But if I make a new singleplayer world, I have no quests completed.

The version is the same on both the client and the server.
The quests are also on the server.

I did a downgrade to version 1604.1.1.21 and everything works correctly now

MC: 1.16.5
Forge: 36.0.14
FTB Quests: 1605.2.0-build27
Architectury: 1.5.110

**Comment by MaxNeedsSnacks** [comment]
You're likely using an obsolete version of Architectury API, please update that to `1.5.110` or higher first

**Comment by Diversion98** [comment]
> You're likely using an obsolete version of Architectury API, please update that to `1.5.110` or higher first

Updated my issue, I'm already running Architectury API 1.5.110

**Comment by LatvianModder** [comment]
Attempt to do all the things you can't do and then upload latest.log

**Comment by Delvious** [comment]
I am having a similar issue where updating quest rewards is also not working on server with the latest version. It works just fine in 1.21 and in the latest version in single player.

**Comment by MaxNeedsSnacks** [comment]
The new update for Architectury should hopefully fix this issue, we fixed some more networking issues

**Comment by Delvious** [comment]
Just updated all mods to latest version. This seemed to fix the issue. Thank you.

**Comment by Diversion98** [comment]
I can confirm that updating Architectury API to version 1.5.112 fixes the quests!

Good job! :D

This issue can be closed.
