### ISSUE TITLE
[1.16.5] Crash when added new item quest

### ISSUE THREAD

**Issue by Alkasym** [FTBTeam/FTB-Quests#538]
Hi,

With the last version of Item Filters, we can't add new item quest, minecraft crash and we can't acces to the quest book after.
No problem with the 1605.2.4.28 version of Item Filters but we can't use ntb in tasks with this version.
To reproduce the probleme, just add new item quest with stone for example and minecraft crash.

Pastbin : https://pastebin.com/paWgia2q

MC: 1.16.5
Forge: 36.0.42
FTB Quests: 1605.2.0-build27
Architectury: 1.6.114
Item Filters : 1605.2.4-build.29

**Comment by Naxanria** [comment]
This has been fixed in build 28, which should be on curseforge soon

**Comment by LatvianModder** [comment]
Fixed in latest

**Comment by Alkasym** [comment]
Thanks you <3
