### ISSUE TITLE
1.16.5  Creating new quests crashes the game

### ISSUE THREAD

**Issue by AlexTheDolphin0** [FTBTeam/FTB-Quests#543]
Whenever I click "accept" on the part where you pick how you complete the quest it crashes the game. 
Here is the crash:
[crash-2021-02-21_01.03.43-client.txt](https://github.com/FTBTeam/FTB-Quests/files/6017318/crash-2021-02-21_01.03.43-client.txt)

**Comment by MaxNeedsSnacks** [comment]
Update Item Filters API to build 29 or higher

**Comment by AlexTheDolphin0** [comment]
okay ty
