### ISSUE TITLE
[1.16.5-Forge] Illegal formatting! Unknown color code character. Issue in Quest descriptions.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Quests#546]
Title^

When trying to add a description to a quest with the symbol "&" you'll get "Illegal formatting" error when saving.

**Example**
``Rewards: 5 EXP Levels & 1x Iron Block`` 

**Will show up like this:**
![image](https://user-images.githubusercontent.com/26634554/108854961-bd140380-75e8-11eb-9b84-f98b0cd21b5b.png)

I'm guessing this is because it thinks I'm trying to put a color code there but I actually just want to have it as a "&" like "and".
This was possible in previous versions of FTB Quests but in the recent ones something broke..

Hoping this can be fixed, because I've got so many of those letters in my quest descriptions and it would be a pain to go through hundreds of quests replacing that symbol to "and" instead..

**Minecraft:** 1.16.5
**Forge:** 36.0.25
**FTB Quests:** 1605.2.0-build.30-forge
**Item-Filters**: 1605.2.4-build.29-forge
**FTB GUI Library:** 1605.2.1.39-forge

Thanks,
**-** Gbergz

**Comment by MaxNeedsSnacks** [comment]
Escape the `&` character using a backslash, & is used to define colors using minecraft colour codes (&9 => dark blue)

**Comment by MaxNeedsSnacks** [comment]
If you want the whole process to be less painful, you could try using a search and replace tool (like `sed` or the advanced search in Visual Studio Code) to replace any occurences of " & " (that is space ampersand space) with " \& " automatically in the .snbt files in the `config/ftbquests` folder.

That **shouldn't** break anything, but just in case it does, be sure to back up your quests before trying that

**Comment by Gbergz** [comment]
Got it to work, did it manually. Wasn't as much as I thought. Thanks though. Appreciate it! :)
