### ISSUE TITLE
Build 31 2/24/2021 release Entity Kill count bug

### ISSUE THREAD

**Issue by ZackTheGoat** [FTBTeam/FTB-Quests#548]
There is an issue with the latest build ftb-quests-1605.2.0-build.31-forge.jar with the Entity Kill quest. A quest set to kill any number  of a mob is completed when only killing one of that mob. (Ex. A quest is set to be completed after killing 100 Zombies, after killing 1 Zombie it is counted as killing 100 Zombies and the quest gets completed.)

**Comment by MaxNeedsSnacks** [comment]
https://github.com/FTBTeam/FTB-Quests/blob/8dd8469a0031ed93ec6d48ed76fe42d54aef1d4b/common/src/main/java/com/feed_the_beast/ftbquests/quest/task/KillTask.java#L140

lat pls

**Comment by MaxNeedsSnacks** [comment]
Currently building the fix, should be up on CurseForge shortly!
https://jenkins.latmod.com/job/FTB-Quests-1.16.3/32/console
