### ISSUE TITLE
Item quest doesn't match nbt

### ISSUE THREAD

**Issue by Alkasym** [FTBTeam/FTB-Quests#551]
Hi,

When I add new item quest with nbt item, to example singularities from extended crafting, all the singularities complete the quest and no the real singularities asked in the quest.
Is there a solution or it's a bug? 

Forge: 36.0.45
FTB Quests: 1605.2.0-build.32
Architectury: 1.8.130
Item Filters : 1605.2.4-build.29

**Comment by MaxNeedsSnacks** [comment]
You should use the NBT Filter from Item Filters for that if I'm not mistaken. That way it'll only match if the nbt of the item is the same

**Comment by Alkasym** [comment]
Oh thanks you it's works fine ! :)
I close the issue.
