### ISSUE TITLE
[Question] How do I make quests where you only need to have a specified amount of the Task items, and not all of them, for the quest to be completed

### ISSUE THREAD

**Issue by Kutomi1** [FTBTeam/FTB-Quests#552]
Basically, I want to make a quest where you need to make either a crude wooden shield or a wooden tower shield, but I can only make it so it requires BOTH items.
Sorry if this feature is already in the mod (1.16 version), in that case I'm dumb for not finding it and I'd like to kindly ask someone to tell me how the heck I can do that. Otherwise, please make this possible, it would be very useful!

**Comment by MaxNeedsSnacks** [comment]
You can use an OR Item Filter to make it so the item task accepts either of these two items.

**Comment by Kutomi1** [comment]
> You can use an OR Item Filter to make it so the item task accepts either of these two items.

Could you tell me where and how I can do that? I can't find any item filter option.
And I also have a problem with loot crates, even if I set a reward table to be a loot crate, it won't give me a loot crate that I have to open by right clicking, instead it just directly gives me the random item. Are loot chests perhaps not implemented in 1.16 yet?
Sorry for all the questions, I don't know any better place to ask these and I'd really like to use this mod.

**Comment by MaxNeedsSnacks** [comment]
Item Filters is a mod you had to install with FTB Quests, there's a physical item you can look up that you can then use in a quest task

**Comment by QiYiJun** [comment]
You can setting "Min Required Dependencies" . Right click on the task and click settings. You can see this option. For example, if it is changed to 2, only the front-end task needs to complete any two tasks.

**Comment by MaxNeedsSnacks** [comment]
What QiYiJun said is also an option, but either way, there *should* be a way to solve your issue on your own, hopefully
