### ISSUE TITLE
Reward tooltips overlapping with other quest icons

### ISSUE THREAD

**Issue by Kutzeee** [FTBTeam/FTB-Quests#553]
![2021-03-04_18 51 18](https://user-images.githubusercontent.com/54329499/110015912-585d5500-7d1c-11eb-9e70-d7755a055030.png)

**Comment by MaxNeedsSnacks** [comment]
What Minecraft version is this?

**Comment by Kutzeee** [comment]
> What Minecraft version is this?

1.16.4 and it's ftb-quests-1605.2.0-build.32-forge

**Comment by MaxNeedsSnacks** [comment]
This should (hopefully) be resolved in newer versions, ~~although Lat likely went crazy while trying to fix it~~
