### ISSUE TITLE
Item task NBT

### ISSUE THREAD

**Issue by Alkasym** [FTBTeam/FTB-Quests#555]
Hi,

I want to create an item task with nbt item.
I use the item filter NBT strong, but, the filter match any item with this NBT and no the Item with the NBT.
To example, I set {value:{Energy:80000,ParticleType:1}} for the Iron jetpack from simply jetpack but any jetpack with this NBT complete the quest.
In the same time, when I click on the item in the quest, there is an issue "No valid items". 
I test with filter AND to have Item AND filter NBT, but it doesn't work.

How to set an item task correctly to have an item with NBT ?

Ps : Sorry for the new issues.
-----------------------------------------------------------------------------------------------------------------------------------
Forge: 36.0.46
FTB Quests: 1605.2.0-build.32
Architectury: 1.8.130
Item Filters : 1605.2.4-build.29

**Comment by MaxNeedsSnacks** [comment]
For the first part: That's how the NBT filter is supposed to work, it'll accept anything as long as the NBT is right.

As for the rest: Can I see a screenshot of the AND filter as well as both of its components? Something doesn't seem right in your setup to me.

**Comment by Alkasym** [comment]
Thanks for your Answer.

This is the screen of the AND filter : 

![questItemNbt](https://user-images.githubusercontent.com/23385822/110114708-5dbaae00-7db5-11eb-8b38-608c06844902.png)

It contains the iron jetpack without NBT and the NBT filter with the NBT.

The full NBT of the AND filter is : {items:[{id:"simplyjetpacks:jetpack_vanilla1",Count:1b},{id:"itemfilters:strong_nbt",Count:1b,tag:{value:{Energy:80000}}}]}
With this setup, the and filter is ok but when I click on the task, there is a "No valid items" information.

**Comment by MaxNeedsSnacks** [comment]
So this is purely a display issue now?

**Comment by Alkasym** [comment]
Yes, the item is doesn't display on the task and create an issue.

**Comment by MaxNeedsSnacks** [comment]
For now I recommend adding a custom icon to the quest, this’ll hopefully be fixed in the future

**Comment by Alkasym** [comment]
Ok thanks you for your help, hope it will be fixed quickly and thanks you for your works 🤞
