### ISSUE TITLE
My quests disappeared

### ISSUE THREAD

**Issue by Origins-Evolution** [FTBTeam/FTB-Quests#559]
I have made quests for my modpack. Then I noticed there is a new version for 1.12.2, so I download it and replace old version in my modpack. But when I restart my game, to my surprise, quests that I have made disappeared! Nothing can be found. What can I do whit it?

**Comment by QiYiJun** [comment]
You can check whether the configuration of ftbquests is reserved in the "config" folder. If not, it's too bad

**Comment by origin-s** [comment]
> You can check whether the configuration of ftbquests is reserved in the "config" folder. If not, it's too bad

I find them. Then I copy them to my config folder and start my game. Although there are some disorderly code in my quests, it helps me a lot. Thank you very much.
