### ISSUE TITLE
Fabric 

### ISSUE THREAD

**Issue by K4dj1t** [FTBTeam/FTB-Quests#560]
Please, make an update for 1.16 fabric

Fabric is a cute modloader with good optimization, better graphics and easier coding. Its already more popular than forge (cause sodium).

And, may i ask a question? Are forestry bees different for this mod?

**Comment by LatvianModder** [comment]
First of all... its already on Fabric.. secondly.. its not even *close* to being as popular as Forge. And thirdly, forestry bees won't usually work because of their extremely complicated NBT

**Comment by aaronhowser1** [comment]
Don't bees have their own task type, or a bee filter or something?
