### ISSUE TITLE
No teams option in Engineers Life 2

### ISSUE THREAD

**Issue by Martizong** [FTBTeam/FTB-Quests#561]
I hosted a EL2 server for me and my friends but theres no option for teams. I searched specific info for the modpack but couldn't find anything, even a forum to ask about this, so i ended up here. 
![image](https://user-images.githubusercontent.com/35152131/111232177-42407600-85f3-11eb-934a-4fb40f8789da.png)
![image](https://user-images.githubusercontent.com/35152131/111232200-4bc9de00-85f3-11eb-84d1-11e529175997.png)

**Comment by Martizong** [comment]
Theres a way to operate through commands, but no GUI unlike other modpacks with FTB Teams and i just found out about it. Closing thread

**Comment by MaxNeedsSnacks** [comment]
Check out #470 as well, Teams are still very much WIP in 1.16
