### ISSUE TITLE
Client crash upon placing Quest Barrier block in multiplayer

### ISSUE THREAD

**Issue by Gitberham** [FTBTeam/FTB-Quests#562]
While testing version upgrades, I keep crashing every time I re-enter the server after placing a Quest Barrier block. This does not happen in singleplayer.

Forge version: 36.1.0 - Minecraft version: 1.16.5
Quests version: ftb-quests-1605.2.1-build.36-forge.jar

**Comment by MaxNeedsSnacks** [comment]
Can you please provide a crash log?

**Comment by Gitberham** [comment]
https://pastebin.com/G9jbN49z

**Comment by MaxNeedsSnacks** [comment]
Fixed by e59a2ef8b7f9f290240711f0bd3689167f84d560
