### ISSUE TITLE
Quest Barrier Blocks still broken after latest update.

### ISSUE THREAD

**Issue by Gitberham** [FTBTeam/FTB-Quests#563]
I am now able to join the server. However, upon placing the block, the block is invisible. Right clicking on this invisible block causes another client-side crash. None of these issues occur in singleplayer.

forge-36.1.0
MC 1.16.5
ftb-quests-1605.2.1-build.37-forge.jar

Crash log:
https://pastebin.com/kZsZdVXR

**Comment by Gitberham** [comment]
Apologies, the invisible blocks were a result of me tampering with resourcepacks. The other issue still stands, though.

**Comment by Gitberham** [comment]
This error also pops up when joining the server

`[08:37:51] [Netty Epoll Server IO #11/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.feed_the_beast.ftbquests.command.QuestObjectArgument@573c75e6 (class com.feed_the_beast.ftbquests.command.QuestObjectArgument) - will not be sent to client!`

**Comment by MaxNeedsSnacks** [comment]
Did build 38 happen to fix this for you?

**Comment by Gitberham** [comment]
Build 38 did fix this for multiplayer, but a new issue now exists where marking a block with a name tag no longer works. Marking the block by directly naming it through an anvil still works, everything else works as intended now.

**Comment by MaxNeedsSnacks** [comment]
Alright, I hopefully managed to fix all known client-server issues with that and change_progress in the recent update, should be out  on CurseForge soon!
