### ISSUE TITLE
Rejoining the server/reloading a singleplayer world makes Quest Barrier blocks solid again

### ISSUE THREAD

**Issue by Gitberham** [FTBTeam/FTB-Quests#564]
Rejoining a server or reloading a single player world turns Quest Barrier blocks into solid blocks again, even though the quest has been completed prior. The only way to fix it is by reapplying the name to the block.

The NBT data is still applied to the block (CTRL + Pick Block and then place) as the block turns green when placed, but for some reason, this doesn't get picked up initially once the world gets loaded. Rejoining after doing this also turns the block solid.

Forge 36.1.0
MC 1.16.5
FTB Quests 1605.2.1-build.39

**Comment by Gitberham** [comment]
Additional information: It seems to be related to chunk loading. I moved away from the position and flew back to load the chunks back in. The blocks turned solid when I did.

**Comment by MaxNeedsSnacks** [comment]
Does this still happen in later versions? My rather janky implementation has since been changed from what I remember, so this SHOULD hopefully be fixed?
