### ISSUE TITLE
[Suggestion]Client setting to keep the chapter panel visible

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Quests#566]
Hello!
I noticed that FTB Quests changed the way chapters show up, they now have full names and the panel expands when the mouse is over it.
As much as I understand it can appeal to some people, I personally prefer the chapters not hiding, I find it easier to use. 
So I was wondering if it'd be possible to add a client setting to let the user choose if the chapter panel hides or not. It'd be greatly appreciated.

Thanks in advance,
Jin

**Comment by NeosGhost** [comment]
bump

**Comment by lrwerewolf** [comment]
I too would appreciate such a setting.  It makes navigation a bit of a pain.

**Comment by Spyro1502** [comment]
each time I open it I wonder why it has been changed this way, I like to have a quick view of everything easily

**Comment by Shadewing666** [comment]
Just adding my voice to the chorus, please add this!

**Comment by Mx772** [comment]
Just to add my 2-cents. I think adding a toggle would be pretty useful here. For designing the quests-lines it's nice to have it hidden, but it seems the first question most people on my server asking when joining is 'How do I make the quest tab stay open'.

**Comment by MichaelHillcox** [comment]
This is a planned feature, no time line, PR's are welcome.

**Comment by Minithra** [comment]
Came here to add my voice to this... playing Seaopolis and it's surprising how much it actually angers me to have to mouse over. Legit anger >.< 

Having the option of keeping the panel with all the quests open without needing a mouse-over would be great!

**Comment by Minithra** [comment]
Bump? the pack I'm playing updated the quests so the panel collapses and it's a serious annoyance.

**Comment by MichaelHillcox** [comment]
Again, this is a planned feature, we hear your annoyance and we want to solve the issue, we have a lot of mods in the works and when we get the time to address this, we will be sure to update this issue.

For now, I'm going to lock the discussion on this chat

**Comment by MaxNeedsSnacks** [comment]
There's now a pin button on the Chapter panel, and we are planning to rework the "flat" version of it, as well.
Thanks for the patience everyone! ;)
