### ISSUE TITLE
The "Dependency Requirement" setting does not work properly

### ISSUE THREAD

**Issue by QiYiJun** [FTBTeam/FTB-Quests#567]
Although I set it to "one started" or "all started", I still need to finish the previous task to start the later task. What should I do? If I don't understand this setting correctly, please let me know.

**Comment by MaxNeedsSnacks** [comment]
Hmm, I'll need to investigate this further, but "started" usually means having partial progress on a task (if that's possible at all), so for example having 1 / 64 apples. Can you show me exactly what does / doesn't work, e.g. through screenshots?

**Comment by QiYiJun** [comment]
> Hmm, I'll need to investigate this further, but "started" usually means having partial progress on a task (if that's possible at all), so for example having 1 / 64 apples. Can you show me exactly what does / doesn't work, e.g. through screenshots?

Such as:
![All Started](https://user-images.githubusercontent.com/60723769/129929584-bea91869-bf7d-4b1a-a586-455c2b1705b4.png)
![One Completed](https://user-images.githubusercontent.com/60723769/129929637-35b13fa7-54e2-4ebb-ada2-df9a3c3f6878.png)
![One Started](https://user-images.githubusercontent.com/60723769/129929724-cde486a3-261b-4659-a863-051cc370e3c4.png)
![All Conpleted](https://user-images.githubusercontent.com/60723769/129929515-70435996-c4ea-4d66-b405-66f653d40c1c.png)

I understand how "One Completed" and "All Completed" work, but I don't understand how "One Started" and "All Started" work.

**Comment by QiYiJun** [comment]
> Hmm, I'll need to investigate this further, but "started" usually means having partial progress on a task (if that's possible at all), so for example having 1 / 64 apples. Can you show me exactly what does / doesn't work, e.g. through screenshots?

Ohhhh! I think I know how "One Started" and "All Started" work.
I think I know how "One Started" and "All Started" work.
"One Started" means we have made some progress, not that we can start.
Is that the right way to understand it?
![2021-08-19_00 10 35](https://user-images.githubusercontent.com/60723769/129933800-24f8d3ce-5d81-4415-bb7f-fc34904eedbb.png)

**Comment by MaxNeedsSnacks** [comment]
I think so yeah, I'm not 100% sure though ^^
