### ISSUE TITLE
Missing Mod Menu Icon

### ISSUE THREAD

**Issue by TrueCP6** [FTBTeam/FTB-Quests#569]
![image](https://user-images.githubusercontent.com/39642832/115279014-7523df80-a146-11eb-8c4d-7fe4c8b7e270.png)
This also applies to all of FTB Quests' dependencies.

**Comment by MaxNeedsSnacks** [comment]
Dangit, must've been a bit hasty with doing the Fabric metadata. I'll check these out and fix them when I get the chance.
