### ISSUE TITLE
(suggestion) NBT option, and Player Detector

### ISSUE THREAD

**Issue by Thunder-Nova** [FTBTeam/FTB-Quests#571]
I did a quest earlier and I have no clue what to do with kubejs and such.

------
So I tried a renamed a name_tag as a quest item, but it still takes a normal name tag without the rename. Either I don't know what I did, or might be that it doesn't detect the NBT.

Simple NBT true or false would suffice if possible.

------
I would like to if it is possible to make an easy "named" player detector... same as before, I have no clue how to use KubeJS.

But would like to set up hidden quest where I can give a pedestal and a head to patreons and youtubers when it detects them when they go online.

------

But if someone can tip me how to make a custom for the ftb quest with these requirements, it helps as well.

**Comment by MaxNeedsSnacks** [comment]
You can detect items with specific NBT by using an NBT filter (see #551)

As for player detectors, that'll still take some time.
