### ISSUE TITLE
reseting quest with command does not reset a choice reward

### ISSUE THREAD

**Issue by benbenlaw** [FTBTeam/FTB-Quests#576]
![image](https://user-images.githubusercontent.com/42780877/116808453-b8ac1f80-ab30-11eb-858e-21bbf5fd025a.png)
after reseting the quest you can still submit items not unablke to claim reward. This does however work with a quests with a set reward

**Comment by LatvianModder** [comment]
Is this the latest dev version? (1605.3.0-build.53)

**Comment by benbenlaw** [comment]
i cant even get the new ftb quests to load as it need gui libary which doesnt download link dont work

**Comment by benbenlaw** [comment]
finally got it to load and no latest version do not fix

**Comment by HopsandBarley** [comment]
Related to this, if you use a command to reset the entire chapter, it doesn't reset the command itself, so you can only do it once.

![image](https://user-images.githubusercontent.com/78277756/132722551-7f6d91f8-05e0-4f48-8bfc-e48a3706affe.png)

**Comment by HopsandBarley** [comment]
Update:  It appears to be just a visual thing.  It does allow you to reset the entire chapter multiple times.
