### ISSUE TITLE
Cant Create a Dimension Quest because it just let me use numbers

### ISSUE THREAD

**Issue by SheroxGG** [FTBTeam/FTB-Quests#580]
I installed FTB quest on my server to create a much better experience, the problem is that Id like to create some quest which can be completed by visiting a specific dimension, the problem comes when I have dimensions that do not have numbers on it, like overworld which is 0, I used a plugin to create world which are called for example ResourceWorld, but for some reason it doesnt let me write that. Hope you can help. Thanks.
![image](https://user-images.githubusercontent.com/34599826/117548356-db5c9d80-b034-11eb-8cf5-4e5319667e12.png)

**Comment by SheroxGG** [comment]
This is my list of worlds.
![image](https://user-images.githubusercontent.com/34599826/117548404-1fe83900-b035-11eb-839e-ac855be26216.png)

**Comment by Osmith0** [comment]
you actually have to use number, each dimension has a numeric id, you can usually find the id of the dimension in the config file 
of the mod you are using

**Comment by MaxNeedsSnacks** [comment]
As @Osmith0 said, if this is pre-1.16, each dimension has a numeric id which you'll have to use for your task ^^
