### ISSUE TITLE
Quest rewards with a quantity of 1 do not show mouseover title

### ISSUE THREAD

**Issue by GregariousJB** [FTBTeam/FTB-Quests#582]
Minecraft 1.16.5
Forge 36.1.13
FTB Quests 1605.2.1

Video showing the bug: https://streamable.com/8gqlrg

This is the same for ALL single quest rewards except for Enchanted Books, for some reason.

On a side note, it'd be nice not to have to enter in a title for each reward and just have the code pull up an automated title for the item, and perhaps be able to be overwritten by the "title" parameter if the user wants to call it something else.

Thank you.

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue in later versions?
