### ISSUE TITLE
AOF3 crash at startup. Fabric/1.16.5

### ISSUE THREAD

**Issue by irunatbullets** [FTBTeam/FTB-Quests#584]
A player in the AOF discord has reported this crash when trying to start the game.

ftbquests: FTB Quests 1605.2.1-build.39

https://paste.alloffabric.com/tifetatowi.yaml

**Comment by MaxNeedsSnacks** [comment]
It seems the AOF team prematurely updated FTB Library without updating Quests as well? Both should be at major version 3 now (albeit being alpha builds still), and FTB Quests requires Teams as well, now

**Comment by irunatbullets** [comment]
Ah okay, user error. We haven't released anything with major version 3. Thanks for the info.
