### ISSUE TITLE
FTB Quests (build 56) Not recognizing latest release of FTB Teams

### ISSUE THREAD

**Issue by willtarax** [FTBTeam/FTB-Quests#585]
According to this image I do not have either FTB Library or FTB Teams (Build 23) installed. I have library, as shown in the second image, and build 23 doesnt exist on Curseforge.

https://imgur.com/a/kiGrHRA

**Comment by koderian** [comment]
+1. Can confirm, Same exact issue as @willtarax. 
`net.minecraftforge.fml.ModLoadingException: Mod §eftbquests§r requires §6ftblibrary§r §o1 or above§r
§7Currently, §6ftblibrary§r§7 is §o§nnot installed`

**Comment by MaxNeedsSnacks** [comment]
FTB Library (ex GUI Library, as it contains a fair bit of non-GUI stuff as well now) and Teams have both received a general do-over and are on CurseForge as alpha builds, which unfortunately don't show up on the client by default. You can still see them in the recent files panel here 
![image](https://user-images.githubusercontent.com/12750501/119045332-984ae480-b9bb-11eb-8f65-73bd20376a8d.png)
and by clicking on "View All" on the downloads page, but these are quite early alphas as well, so they shouldn't be used by the wider public yet (Is Quests tagged as a release version by mistake?)

**Comment by MaxNeedsSnacks** [comment]
Honestly if your pack is still in development you can stick with all of the newer versions (provided you download **all** of them).

We will soon:tm: have proper releases out as well but these just need to be tested before we can actually release em to the public

**Comment by willtarax** [comment]
Alright, I'll see what I dont have, and see if that fixes it. Thank you.

**Comment by TheWitherlord** [comment]
This error only seems to happen in the latest version of forge for me.
