### ISSUE TITLE
[1.12.2] Players with similar nicknames gets progress from others teams

### ISSUE THREAD

**Issue by Weylend** [FTBTeam/FTB-Quests#586]
1. Create team 
2. Complete some quests
3. Join to the server from another profile with nickname that contains team name
Example: team is "weylend" you need to login as "weylen"
4. You will get quest progress from this teams with all rewards

Magma Dev HEAD-48ec0a1
FTBQuests-1202.9.0.15
FTBLib-5.4.7.2

**Comment by BartolomeoDR** [comment]
☺ wow.

**Comment by MaxNeedsSnacks** [comment]
Wow, indeed... This **shouldn't** be happening in more recent Minecraft versions, anyways, and we've basically completely dropped 1.12 support for our mods, but if you can someone how reproduce this ***without server mods*** specifically, so no Bukkit/Spigot/Sponge, this seems like quite a **critical** bugfix we may need to push
