### ISSUE TITLE
Cannot fully delete quest descriptions

### ISSUE THREAD

**Issue by pm065** [FTBTeam/FTB-Quests#587]
Say I wanted to make a quest without a description:
![image](https://user-images.githubusercontent.com/81559564/119612676-15c78800-bdf4-11eb-8e30-840b51e34bb5.png)

But then I change my mind and add one:
![image](https://user-images.githubusercontent.com/81559564/119612812-3e4f8200-bdf4-11eb-9355-6859e4b7cb64.png)

But then I change my mind again and decide I don't want a description, so I delete the text in the Description section:
![image](https://user-images.githubusercontent.com/81559564/119612960-6f2fb700-bdf4-11eb-9959-0cb1c6cf6866.png)

However, the mod seems to interpret the remaining top line - which cannot be removed - as an intended line break, meaning the quest now looks like this:
![image](https://user-images.githubusercontent.com/81559564/119613182-9f775580-bdf4-11eb-9909-ab5ef57d820c.png)

Note the blank space where the description used to be.

**Comment by TheDeviantCrafter** [comment]
In an older version of the mod, empty lines would delete themselves after 5-10 seconds. I haven't seen that happen recently though.

**Comment by Jake-E** [comment]
What font are you using?

**Comment by MaxNeedsSnacks** [comment]
1. Thanks Jake 😄 
2. This **should** be fixed using the new inline description editor? (Which, the old one you're using here will hopefully be phased out soon anyways) If it isn't please feel free to reopen ^^
