### ISSUE TITLE
Not able to claim rewards normaly or choice rewards at all

### ISSUE THREAD

**Issue by adh92100** [FTBTeam/FTB-Quests#591]
I am playing all the mods, all the magic by ATMTeam and while fulfilling the quests I notice that the normal way of clicking on the reward from the quest was not working and the only way to get a reward is to go to the golden apple for unclaimed rewards and except it that way. But if the reward is a choice between multiple items, clicking the one you want dosent work and going to the unclaimed rewards just gives a blank screen with only the close botton to press.

**Comment by MaxNeedsSnacks** [comment]
I can't seem to reproduce this myself, unfortunately, so this seems to be a pack issue :/
