### ISSUE TITLE
Crash when entering the 'select item' screen

### ISSUE THREAD

**Issue by pm065** [FTBTeam/FTB-Quests#592]
FTB Quests: 1605.3.2-build.10
FTB Lib: 1605.3.1-build.12
Crash report: https://paste.ee/p/s2SHT
Rolling back one version on Quests, Teams and Lib fixes the issue.

**Comment by ReeCodes** [comment]
Same

**Comment by MaxNeedsSnacks** [comment]
Duplicate of #602, I'm assuming
