### ISSUE TITLE
[bug] We can't create quest in server.

### ISSUE THREAD

**Issue by MathisSkate** [FTBTeam/FTB-Quests#594]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.
**FTB Quest Version**
ftb-quests-forge-1605.3.2-build.14

**Forge / Fabric version, if applicable**
Forge 1.16.5 - 36.1.25

**How to reproduce the issue**
*Please provide use with a step by step description*
We can't create quest in server.

**Comment by Larkin10859** [comment]
We are having this same issue on our server. 

FTB Quest Version
ftb-quests-forge-1605.3.2-build.14

Forge 1.16.5 - 36.1.25

**Comment by MaxNeedsSnacks** [comment]
I'll need a bit more information to be able to help you.

(1) Are you in editing mode?
(2) Can you make quests in Singleplayer?
(3) What's actually broken here, can you just not do anything at all, do the quests not synchronise between you and your friends, what's going on?

**Comment by Larkin10859** [comment]
Hey max we are a different server than Mathais but I will answer for our server

(1) Are you in editing mode? Yes. 2 Editors have attempted. It also seems to tie editing mode to team now and not person. 
(2) Can you make quests in Singleplayer? We have not checked that as once we saw the issue we just joined in to provide that it is reproducible 
(3) What's actually broken here, can you just not do anything at all, do the quests not synchronise between you and your friends, what's going on? Following the steps to add the quest everything works, but then the quest does not show and does not register as exsisting.

**Comment by MathisSkate** [comment]
Hey !
(1) Are you in editing mode? Yes
(2) Can you make quests in Singleplayer? Yes i have start une singleplayer no problem et in server  we can't
(3) What's actually broken here, can you just not do anything at all, do the quests not synchronise between you and your friends, what's going on? All works but we can't create any type of quests in server

**Comment by Powerkhan** [comment]
Using Forge alpha build 18 i can create chapters and chapter groups (shown in first image.
all dialog windows open when trying to add in a quest/reward (image 2 is example of item 3rd is xp and 4th is kill entity)
allows perfectly editing of everything. but clicking "done" to set the quest in motion everything remains blank (see image 5)

![image](https://user-images.githubusercontent.com/78354069/121799408-f1dcb280-cbf9-11eb-9e46-f864d55c4daf.png)
![image](https://user-images.githubusercontent.com/78354069/121799416-002ace80-cbfa-11eb-90ec-0db51ea3330a.png)
![image](https://user-images.githubusercontent.com/78354069/121799425-0751dc80-cbfa-11eb-88a3-331d0ea2f52f.png)
![image](https://user-images.githubusercontent.com/78354069/121799431-0faa1780-cbfa-11eb-9243-b686678a7140.png)
![image](https://user-images.githubusercontent.com/78354069/121799433-15076200-cbfa-11eb-828c-233af2169fa9.png)

Yes i have editing access owner of multiplayer server using /ftbquests editing_mode
alpha build is ftb-quests-forge-1605.3.2-build.18.jar
also using FTB files for:
ftb-backups-2.1.1.6.jar
ftb-chunks-1605.2.3-build.75.jar
ftb-essentials-1604.1.0.13.jar
ftb-gui-library-1605.2.1.41-forge.jar
ftb-library-forge-1605.3.1-build-23
ftb-teams-forge-1605.2.1-build.12.jar
and ftb-ultimine-forge-1605.2.2-build.4.jar

also using pmmo alpha build Project_mmo-1.16.5-3.58.2.jar

if you need anything else let me know here or on the discord. (Powerboss there :-) )

**Comment by NathanLithia** [comment]
Also have this issue, cannot edit/create quests

ftb-backups-2.1.1.6.jar
ftb-chunks-forge-1605.3.1-build.16.jar
ftb-essentials-1605.1.2-build.20.jar
ftb-library-forge-1605.3.1-build.23.jar
ftb-quests-forge-1605.3.2-build.18.jar
ftb-ranks-1605.1.2-build.17-forge.jar
ftb-teams-forge-1605.2.1-build.12.jar

**Comment by keeper317** [comment]
> (1) Are you in editing mode? 
-Yes
> (2) Can you make quests in Singleplayer? 
-Yes, on server it gives an [error](https://ghostbin.co/paste/82oyf2a): ` Error executing task on Server java.lang.NullPointerException: Client quest file not loaded!` Full log below.
> (3) What's actually broken here, can you just not do anything at all, do the quests not synchronise between you and your friends, what's going on? 
-Attempting to add a quest to a chapter appears to work until clicking accept at which point the [error ](https://ghostbin.co/paste/82oyf2a) is shown in the server console and the quest fails to appear in the menu. The book in the top left also fails to open the menu for me when I click but does not give an error.
-Mods:
    architectury-1.17.22-forge.jar
    ftb-gui-library-1605.2.1.41-forge.jar
    ftb-library-forge-1605.3.1-build.23.jar
    ftb-quests-forge-1605.3.2-build.18.jar
    ftb-teams-forge-1605.2.1-build.12.jar
    item-filters-1605.2.4-build.30-forge.jar

https://ghostbin.co/paste/82oyf2a

**Comment by keeper317** [comment]
> > (1) Are you in editing mode?
> > -Yes
> > (2) Can you make quests in Singleplayer?
> > -Yes, on server it gives an [error](https://ghostbin.co/paste/82oyf2a): ` Error executing task on Server java.lang.NullPointerException: Client quest file not loaded!` Full log below.
> > (3) What's actually broken here, can you just not do anything at all, do the quests not synchronise between you and your friends, what's going on?
> > -Attempting to add a quest to a chapter appears to work until clicking accept at which point the [error ](https://ghostbin.co/paste/82oyf2a) is shown in the server console and the quest fails to appear in the menu. The book in the top left also fails to open the menu for me when I click but does not give an error.
> > -Mods:
> > architectury-1.17.22-forge.jar
> > ftb-gui-library-1605.2.1.41-forge.jar
> > ftb-library-forge-1605.3.1-build.23.jar
> > ftb-quests-forge-1605.3.2-build.18.jar
> > ftb-teams-forge-1605.2.1-build.12.jar
> > item-filters-1605.2.4-build.30-forge.jar
> 
> https://ghostbin.co/paste/82oyf2a

Not sure if it matters, but I am able to make a quest chapter in singleplayer with as many quests as I want and then put it on a server and it works fine, but still can't add anything on the server.

**Comment by MaxNeedsSnacks** [comment]
> > > (1) Are you in editing mode?
> > > -Yes
> > > (2) Can you make quests in Singleplayer?
> > > -Yes, on server it gives an [error](https://ghostbin.co/paste/82oyf2a): ` Error executing task on Server java.lang.NullPointerException: Client quest file not loaded!` Full log below.
> > > (3) What's actually broken here, can you just not do anything at all, do the quests not synchronise between you and your friends, what's going on?
> > > -Attempting to add a quest to a chapter appears to work until clicking accept at which point the [error ](https://ghostbin.co/paste/82oyf2a) is shown in the server console and the quest fails to appear in the menu. The book in the top left also fails to open the menu for me when I click but does not give an error.
> > > -Mods:
> > > architectury-1.17.22-forge.jar
> > > ftb-gui-library-1605.2.1.41-forge.jar
> > > ftb-library-forge-1605.3.1-build.23.jar
> > > ftb-quests-forge-1605.3.2-build.18.jar
> > > ftb-teams-forge-1605.2.1-build.12.jar
> > > item-filters-1605.2.4-build.30-forge.jar
> > 
> > 
> > https://ghostbin.co/paste/82oyf2a
> 
> Not sure if it matters, but I am able to make a quest chapter in singleplayer with as many quests as I want and then put it on a server and it works fine, but still can't add anything on the server.

Right, this is ***exactly*** the report I needed to actually figure this out, thanks!

Lat has pushed a build that should fix this with https://github.com/FTBTeam/FTB-Quests/commit/c0b744ed00a6dbebc165ebcd874c456796467ae1, look out for build number 20 on CurseForge!
