### ISSUE TITLE
Multiblock Structure Task

### ISSUE THREAD

**Issue by generrosity** [FTBTeam/FTB-Quests#60]
While watching every single block placement might be quite an excessive overhead, it would be very cool to be able to "see" when a player has finished forming a structure.

Thinking about supporting exploration and building packs, as they often can't easily be catered for. I particularly would like to set up a specific structure for locations around the world.

Potentially, it might need the quest book to boop a specific block to trigger the check (or on quest book opening, or on each block place, by a ftbq option?)

Otherwise, is it possible to detect the creation of multiblock structures, or the tile that represents it? Or interaction with one? At the moment, requiring a dummy craft from eg a Astral Sorcery alter.

**Comment by LatvianModder** [comment]
I thought about this before and decided that Screen would be best required for this task. To build a structure in front of it would be enough, no complex world-destroying checks on every placement or anything

**Comment by generrosity** [comment]
That makes a lot of sense. Would it check 'infront' of every screen or just one that has a specific display? I imagine it would not allow for the structure to be eg entirely one block to the left.

Thinking again about world exploration quests ... how viable would it be to Give a player a specific screen to place in the world, and then build against? But thematically, it would possibly be better to have a "structure" block incorporated into the structure itself (which then could be replaced by a block, a reward chest, etc).

**Comment by kreezxil** [comment]
i'd be very interested in placing a bounty on this.

How much of donation do you require to make this be a priority?

**Comment by generrosity** [comment]
@kreezxil incase you haven't seen traction, Latvian does the majority of his discussion on [Discord](https://discord.gg/bPFfH6P) rather than on Github

**Comment by kreezxil** [comment]
@generrosity you started the thread. How much has it helped for you to join his Discord?

**Comment by Breadabix** [comment]
Hi, I am trying to make quests in a modpack for me and friends, and im trying to find if there is a way for this mod to detect structures. Did building in front of task screens ever get implemented or is there no way to detect structures. Thanks
