### ISSUE TITLE
[bug] We can't set weight of items in lootrewards

### ISSUE THREAD

**Issue by MathisSkate** [FTBTeam/FTB-Quests#601]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
ftb-quests-forge-1605.3.2-build.16

**Forge / Fabric version, if applicable**
Forge 36.1.31

**Modpack (with version), if applicable**
Mine

**How to reproduce the issue**
*Please provide use with a step by step description*
Create loot table, add items in loot table set the weight of item save the loot table and you will see the weight is 0

**Comment by LatvianModder** [comment]
Can you try this dev build and see if that fixed it?

https://maven.saps.dev/minecraft/dev/ftb/mods/ftb-quests-forge/1605.3.2-build.17/ftb-quests-forge-1605.3.2-build.17.jar

**Comment by MathisSkate** [comment]
That's works ! 

This build fix the server side bug ?

**Comment by LatvianModder** [comment]
Not sure what server bug, but this version has been pushed to CurseForge so build 18 will be there soon

**Comment by MathisSkate** [comment]
Ok thanks !

**Comment by MathisSkate** [comment]
the serveur bug is this #594

**Comment by MaxNeedsSnacks** [comment]
This *should* be fixed in more recent versions I think? If not feel free to reopen this ^^
