### ISSUE TITLE
[bug] (Alpha Version 1605.2.1-build.39) FTB Quest becomes non functional after creating a Team party

### ISSUE THREAD

**Issue by Harve** [FTBTeam/FTB-Quests#606]
FTB Teams Version: forge-1605.2.1-build.12.jar
FTB Quest Version: forge-1605.3.3-build.26.jar
FTB Library Version:  forge-1605.3.1-build.33.jar
Modpack: Go Create

FTB Quests functions as expected until /ftbteams party create is performed, then FTB Quests becomes completely non functional as quests cannot be completed and rewards cannot be claimed. Leaving the party makes FTB Quests work again.
Repeatable every time I do this on 2 different machines running the same modpack.
No error present in log.

**Comment by MaxNeedsSnacks** [comment]
This is a client-server desync that should be resolved in the latest release
