### ISSUE TITLE
[feature] Adding quest reset in the rewards

### ISSUE THREAD

**Issue by ItayKisous** [FTBTeam/FTB-Quests#607]
The feature of reseting a quest should be good for pack makers that want to make a shop inside the book.
/ftbquests change_progress @p reset questid - has been removed + it wouldn't reset the rewards.

**Comment by mortuusars** [comment]
I've spent an hour creating quests to sell items for coins. And then realized that you can't make them repeatable, lol.

Option to make them repeatable would be very nice.

**Comment by ItayKisous** [comment]
> I've spent an hour creating quests to sell items for coins. And then realized that you can't make them repeatable, lol.
> 
> 
> 
> Option to make them repeatable would be very nice.

I found out you can.
You need to do a command quest with /ftbquests change_progress @p reset ChapterID
Don't do it as player command cuz it will require operator

**Comment by mortuusars** [comment]
> I found out you can.
> You need to do a command quest with /ftbquests change_progress @p reset ChapterID
> Don't do it as player command cuz it will require operator

Thanks. This works, but it has some limitations. I would still prefer an option to make a single quest repeatable.

**Comment by MaxNeedsSnacks** [comment]
Yeah, repetable quests are coming back *eventually*, but they'e an absolute *pain* to get right unfortunately since there are quite a few edge cases associated with them (like depending on a repeatable quest, which would perma-lock the dependant) :/
