### ISSUE TITLE
[bug] Opening Quest book

### ISSUE THREAD

**Issue by szumaster** [FTBTeam/FTB-Quests#612]
### **Mod & Pack version**
- ftb-quests-fabric-1605.3.3-build.39
- ftb-teams-fabric-1605.2.1-build.17
- ftb-library-fabric-1605.3.1-build.48

### **Forge / Fabric version, if applicable**
- 1.16.5 0.11.6

### **If the issue is a crash; An external link to the crash report**
- https://pastebin.com/q3jExSHE

### **How to reproduce the issue**
1. run mc
2. ftbquests editing_mode
3. add anything to new chapter including img 
4. relog 
5. open quest book -> crash

**Comment by LatvianModder** [comment]
Looks like a faulty icon of chapter somewhere
