### ISSUE TITLE
[feature] Chat Announcement

### ISSUE THREAD

**Issue by VampireTechnologyLord** [FTBTeam/FTB-Quests#613]
I would like a feature, most likely toggleable in the config file, that announces to the chat, when someone has completed a quest or a  quest chapter. In my imagination, it looks like this, but if there are different ways to do it, then please do it that way :smile: :

#### For a quest:
> [FTBQUESTS] PLAYERNAME has completed the quest 'QUESTNAME'

#### For a chapter:
> [FTBQUESTS] PLAYERNAME has completed the chapter 'CHAPTERNAME'

-----------

Maybe, you could also add hover text to the messages like this:

#### For a quest:
```
Name: QuestName
ID: QuestID
Chapter: Chaptername
Chaptergroup: Chaptergroupname
Requirements:
 - Required Quest 1
 - Required Quest 2
Unlocks:
 - Child Quest 1
 - Child Quest 2
```

#### For a chapter:
```
Chapter: Chaptername
Chaptergroup: Chaptergroupname
```

**Comment by MaxNeedsSnacks** [comment]
You can achieve this using command rewards (and in the case of the chapter, an invisible quest somewhere that **depends** on that chapter and uses a similar command reward)
