### ISSUE TITLE
[bug] Items don't appear and the game crashes

### ISSUE THREAD

**Issue by BovineShaman** [FTBTeam/FTB-Quests#614]
**Mod & Pack version**
FTB Quests: 1605.3.3-build.39

**Forge / Fabric version, if applicable**
Forge: 36.2.0

**Modpack (with version), if applicable**
ATM6: 1.7.3

**Crashlog:** https://pastebin.com/43biYwXd

**How to reproduce the issue**
1. Launch the pack
2. Load into a singleplayer world, already have FTB Quests editing mode on from previous session
3. Open FTB Quests menu
4. right click to add an a quest, click item (anything really)
5. No items appear (screenshot below)
6. trying to click on other stuff crashes the game after that

**[Screenshot](https://cdn.discordapp.com/attachments/690026962420367579/868350717377781790/unknown.png)**

**Anything else we should know?**
I've tried updating the pack, restarting the game, computer, etc. Haven't gotten items to actually show up.
I am pretty much completely unable to modify or add/remove quests using the in-game editor.

**Comment by BovineShaman** [comment]
Same as #602, actually

**Comment by MaxNeedsSnacks** [comment]
Yea, it's the same issue as #602, gonna ask @LatvianModder to try the fix outlined in https://github.com/FTBTeam/FTB-Quests/issues/602#issuecomment-882014111 for now
