### ISSUE TITLE
[bug] Curseforge downgrades from build 49 to 39 when updating ftbquests

### ISSUE THREAD

**Issue by szunakabeats** [FTBTeam/FTB-Quests#616]
how to reproduce:

- make a new 1.16.5 forge instance.
- click on add more content
- install ftb quests
- curseforge says "update" on ftb quests
- when updating the version goes down

**Comment by MichaelHillcox** [comment]
Are the main versions different, can you show both versions?

**Comment by szunakabeats** [comment]
what do you mean with main versions ?

**Comment by MaxNeedsSnacks** [comment]
FTB reset its build versions recently, so we went from say, `3.1.build-100` to `3.2.build-1`
The important bit is that you're using the most recent available **release** file on CurseForge (or beta if you don't mind experimental features), so the one that should hopefully be at the top of the list
