### ISSUE TITLE
[bug] Team Data not visible when re-login on dedicated server

### ISSUE THREAD

**Issue by yuesha-yc** [FTBTeam/FTB-Quests#617]
**Mod & Pack version**
ftb-teams-forge-1605.2.1-build.20
ftb-quests-forge-1605.3.3-build.49

**Forge / Fabric version, if applicable**
Forge

**How to reproduce the issue**
On dedicated server, 

Use `/ftbteams server create`  to create a team
Log off server
Log in server again
The team quest data disappears
Only when you use `/ftbteams server create` again, you will have the data again. 

I believe this is a bug and not an intended design.

**Comment by MaxNeedsSnacks** [comment]
You are creating ***server*** teams, which are meant for spawn areas, admin shops, etc.
Try using **party teams** (server teams shouldn't even support quests, so what you've described here is still weird)
