### ISSUE TITLE
[bug] FTBQuestsInventoryListener causing some lag

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Quests#628]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
1605.3.4-build52
**Forge / Fabric version, if applicable**
Forge 36.2.2
**Modpack (with version), if applicable**
Chroma Technology 2

**How to reproduce the issue**
Not quite sure how to reproduce it but it looks like spark is reporting some heavy ticking from FTBQuestsInventoryListener. Here's the report : https://spark.lucko.me/OC5hKFD5cb

That report was with about 6-7 players online

**Comment by jinkhya** [comment]
Hello again, I may have a lead on this.

I have noticed that forge track entity sometimes report players as very high ticking entities (which also shows in that spark report) but not all players were showing. I narrowed it down and it seems to happen to people using time in a bottle. 

Could the FTBQuestsInventoryListener cause some lag because the time in a bottle constantly updates as it builds time and ftbquests checks it constantly in case it'd match a quest?

**Comment by LatvianModder** [comment]
Hmm, yeah, I see. I think I can just check if **item** changes? That may break very few quests that require specific tag on item but without the item moving its slot (for example, if you activate some item that uses `{Active:true}` tag and that tag is required for quest) but overall I think that will benefit massively
