### ISSUE TITLE
Task Conditions

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Quests#83]
E.g. "Item in inventory", "XP Level > x", "Dimension == Nether" etc. Could be assigned to each task

**Comment by Dragnier** [comment]
It would also be nice to have a checkbox task. Something just to give the player information and have them acknowledge they have read it.

**Comment by LatvianModder** [comment]
Make that a seperate suggestion

**Comment by MaxNeedsSnacks** [comment]
This can be done with KubeJS now.
